In [1]:
import os
import json
import requests
from dotenv import load_dotenv

In [2]:
load_dotenv()

api_key = os.getenv("api_key")

In [ ]:
load_dotenv()

url = f'https://v6.exchangerate-api.com/v6/{api_key}/latest/EUR'

response = requests.get(url)
data = response.json()

In [ ]:
print(data)

{'result': 'success', 'documentation': 'https://www.exchangerate-api.com/docs', 'terms_of_use': 'https://www.exchangerate-api.com/terms', 'time_last_update_unix': 1772377202, 'time_last_update_utc': 'Sun, 01 Mar 2026 15:00:02 +0000', 'time_next_update_unix': 1772380802, 'time_next_update_utc': 'Sun, 01 Mar 2026 16:00:02 +0000', 'base_code': 'EUR', 'conversion_rates': {'EUR': 1, 'AED': 4.3367241, 'AFN': 74.77254346, 'ALL': 96.25234219, 'AMD': 445.45273414, 'ANG': 2.11374708, 'AOA': 1093.07993363, 'ARS': 1714.91016214, 'AUD': 1.6610667, 'AWG': 2.11374708, 'AZN': 2.00800286, 'BAM': 1.95583, 'BBD': 2.36172858, 'BDT': 144.34372209, 'BGN': 1.95583, 'BHD': 0.44400497, 'BIF': 3505.38244031, 'BMD': 1.18086429, 'BND': 1.494261, 'BOB': 8.17697435, 'BRL': 6.06959697, 'BSD': 1.18086429, 'BTN': 107.529955, 'BWP': 15.87490199, 'BYN': 3.40067962, 'BZD': 2.36172858, 'CAD': 1.61213463, 'CDF': 2693.41791045, 'CHF': 0.90915042, 'CLF': 0.02601494, 'CLP': 1028.30927832, 'CNH': 8.10288769, 'CNY': 8.10967488, 'COP': 4399.15198846, 'CRC': 558.62143448, 'CUP': 28.34074291, 'CVE': 110.265, 'CZK': 24.24169306, 'DJF': 209.86438211, 'DKK': 7.46130519, 'DOP': 70.57489392, 'DZD': 153.4957875, 'EGP': 56.63840592, 'ERN': 17.71296432, 'ETB': 184.55254193, 'FJD': 2.58927762, 'FKP': 0.87627504, 'FOK': 7.46130507, 'GBP': 0.87627699, 'GEL': 3.15856908, 'GGP': 0.87627504, 'GHS': 12.61893498, 'GIP': 0.87627504, 'GMD': 87.60801491, 'GNF': 10315.32309257, 'GTQ': 9.05936197, 'GYD': 247.20410959, 'HKD': 9.24146741, 'HNL': 31.26068945, 'HRK': 7.5345, 'HTG': 154.9669386, 'HUF': 376.53460858, 'IDR': 19836.41808675, 'ILS': 3.70560032, 'IMP': 0.87627504, 'INR': 107.53003913, 'IQD': 1549.00429185, 'IRR': 1549080.10399209, 'ISK': 143.4759794, 'JEP': 0.87627504, 'JMD': 184.47373311, 'JOD': 0.83723278, 'JPY': 184.32093499, 'KES': 152.37206462, 'KGS': 103.31819397, 'KHR': 4748.92105263, 'KID': 1.66106564, 'KMF': 491.96775, 'KRW': 1702.28359283, 'KWD': 0.36121485, 'KYD': 0.98405318, 'KZT': 588.75056337, 'LAK': 25739.86406979, 'LBP': 105687.35376912, 'LKR': 365.05520339, 'LRD': 216.75754763, 'LSL': 18.82581767, 'LYD': 7.46129993, 'MAD': 10.81032401, 'MDL': 20.12036937, 'MGA': 4944.07255235, 'MKD': 61.6948, 'MMK': 2488.32866164, 'MNT': 4187.31120363, 'MOP': 9.51870717, 'MRU': 47.3148925, 'MUR': 54.70899555, 'MVR': 18.26241842, 'MWK': 2052.14400917, 'MXN': 20.34547218, 'MYR': 4.59522355, 'MZN': 75.56564591, 'NAD': 18.82581767, 'NGN': 1602.21794304, 'NIO': 43.46389765, 'NOK': 11.23618761, 'NPR': 172.04792799, 'NZD': 1.97122024, 'OMR': 0.45403878, 'PAB': 1.18086429, 'PEN': 3.96306142, 'PGK': 5.14832622, 'PHP': 68.15071503, 'PKR': 330.34660177, 'PLN': 4.22446344, 'PYG': 7671.35778313, 'QAR': 4.29834601, 'RON': 5.09496799, 'RSD': 117.45284427, 'RUB': 91.32497354, 'RWF': 1719.68830874, 'SAR': 4.42824108, 'SBD': 9.47793654, 'SCR': 16.50242043, 'SDG': 528.43045388, 'SEK': 10.66776006, 'SGD': 1.49426181, 'SHP': 0.87627504, 'SLE': 28.90767626, 'SLL': 28907.63334995, 'SOS': 674.61308411, 'SRD': 44.64044527, 'SSP': 5414.00038168, 'STN': 24.5, 'SYP': 136.06281912, 'SZL': 18.82581767, 'THB': 36.68753069, 'TJS': 11.08250568, 'TMT': 4.13311592, 'TND': 3.38025198, 'TOP': 2.77430317, 'TRY': 51.91632718, 'TTD': 8.73247311, 'TVD': 1.66106564, 'TWD': 37.06397753, 'TZS': 3021.15819273, 'UAH': 50.94735429, 'UGX': 4232.41084654, 'USD': 1.18086604, 'UYU': 45.41528357, 'UZS': 14420.95619518, 'VES': 495.60601336, 'VND': 30378.23545301, 'VUV': 139.14860152, 'WST': 3.17029742, 'XAF': 655.957, 'XCD': 3.18833358, 'XCG': 2.11374708, 'XDR': 0.85842046, 'XOF': 655.957, 'XPF': 119.332, 'YER': 281.50747131, 'ZAR': 18.8258267, 'ZMW': 22.23348828, 'ZWG': 30.44219996, 'ZWL': 30.4422}}

In [8]:
print(json.dumps(data, indent=2))

{
  "result": "success",
  "documentation": "https://www.exchangerate-api.com/docs",
  "terms_of_use": "https://www.exchangerate-api.com/terms",
  "time_last_update_unix": 1772377202,
  "time_last_update_utc": "Sun, 01 Mar 2026 15:00:02 +0000",
  "time_next_update_unix": 1772380802,
  "time_next_update_utc": "Sun, 01 Mar 2026 16:00:02 +0000",
  "base_code": "EUR",
  "conversion_rates": {
    "EUR": 1,
    "AED": 4.3367241,
    "AFN": 74.77254346,
    "ALL": 96.25234219,
    "AMD": 445.45273414,
    "ANG": 2.11374708,
    "AOA": 1093.07993363,
    "ARS": 1714.91016214,
    "AUD": 1.6610667,
    "AWG": 2.11374708,
    "AZN": 2.00800286,
    "BAM": 1.95583,
    "BBD": 2.36172858,
    "BDT": 144.34372209,
    "BGN": 1.95583,
    "BHD": 0.44400497,
    "BIF": 3505.38244031,
    "BMD": 1.18086429,
    "BND": 1.494261,
    "BOB": 8.17697435,
    "BRL": 6.06959697,
    "BSD": 1.18086429,
    "BTN": 107.529955,
    "BWP": 15.87490199,
    "BYN": 3.40067962,
    "BZD": 2.36172858,
    "CAD": 1.61213463,
    "CDF": 2693.41791045,
    "CHF": 0.90915042,
    "CLF": 0.02601494,
    "CLP": 1028.30927832,
    "CNH": 8.10288769,
    "CNY": 8.10967488,
    "COP": 4399.15198846,
    "CRC": 558.62143448,
    "CUP": 28.34074291,
    "CVE": 110.265,
    "CZK": 24.24169306,
    "DJF": 209.86438211,
    "DKK": 7.46130519,
    "DOP": 70.57489392,
    "DZD": 153.4957875,
    "EGP": 56.63840592,
    "ERN": 17.71296432,
    "ETB": 184.55254193,
    "FJD": 2.58927762,
    "FKP": 0.87627504,
    "FOK": 7.46130507,
    "GBP": 0.87627699,
    "GEL": 3.15856908,
    "GGP": 0.87627504,
    "GHS": 12.61893498,
    "GIP": 0.87627504,
    "GMD": 87.60801491,
    "GNF": 10315.32309257,
    "GTQ": 9.05936197,
    "GYD": 247.20410959,
    "HKD": 9.24146741,
    "HNL": 31.26068945,
    "HRK": 7.5345,
    "HTG": 154.9669386,
    "HUF": 376.53460858,
    "IDR": 19836.41808675,
    "ILS": 3.70560032,
    "IMP": 0.87627504,
    "INR": 107.53003913,
    "IQD": 1549.00429185,
    "IRR": 1549080.10399209,
    "ISK": 143.4759794,
    "JEP": 0.87627504,
    "JMD": 184.47373311,
    "JOD": 0.83723278,
    "JPY": 184.32093499,
    "KES": 152.37206462,
    "KGS": 103.31819397,
    "KHR": 4748.92105263,
    "KID": 1.66106564,
    "KMF": 491.96775,
    "KRW": 1702.28359283,
    "KWD": 0.36121485,
    "KYD": 0.98405318,
    "KZT": 588.75056337,
    "LAK": 25739.86406979,
    "LBP": 105687.35376912,
    "LKR": 365.05520339,
    "LRD": 216.75754763,
    "LSL": 18.82581767,
    "LYD": 7.46129993,
    "MAD": 10.81032401,
    "MDL": 20.12036937,
    "MGA": 4944.07255235,
    "MKD": 61.6948,
    "MMK": 2488.32866164,
    "MNT": 4187.31120363,
    "MOP": 9.51870717,
    "MRU": 47.3148925,
    "MUR": 54.70899555,
    "MVR": 18.26241842,
    "MWK": 2052.14400917,
    "MXN": 20.34547218,
    "MYR": 4.59522355,
    "MZN": 75.56564591,
    "NAD": 18.82581767,
    "NGN": 1602.21794304,
    "NIO": 43.46389765,
    "NOK": 11.23618761,
    "NPR": 172.04792799,
    "NZD": 1.97122024,
    "OMR": 0.45403878,
    "PAB": 1.18086429,
    "PEN": 3.96306142,
    "PGK": 5.14832622,
    "PHP": 68.15071503,
    "PKR": 330.34660177,
    "PLN": 4.22446344,
    "PYG": 7671.35778313,
    "QAR": 4.29834601,
    "RON": 5.09496799,
    "RSD": 117.45284427,
    "RUB": 91.32497354,
    "RWF": 1719.68830874,
    "SAR": 4.42824108,
    "SBD": 9.47793654,
    "SCR": 16.50242043,
    "SDG": 528.43045388,
    "SEK": 10.66776006,
    "SGD": 1.49426181,
    "SHP": 0.87627504,
    "SLE": 28.90767626,
    "SLL": 28907.63334995,
    "SOS": 674.61308411,
    "SRD": 44.64044527,
    "SSP": 5414.00038168,
    "STN": 24.5,
    "SYP": 136.06281912,
    "SZL": 18.82581767,
    "THB": 36.68753069,
    "TJS": 11.08250568,
    "TMT": 4.13311592,
    "TND": 3.38025198,
    "TOP": 2.77430317,
    "TRY": 51.91632718,
    "TTD": 8.73247311,
    "TVD": 1.66106564,
    "TWD": 37.06397753,
    "TZS": 3021.15819273,
    "UAH": 50.94735429,
    "UGX": 4232.41084654,
    "USD": 1.18086604,
    "UYU": 45.41528357,
    "UZS": 14420.95619518,
    "VES": 495.60601336,
    "VND": 30378.23545301,
    "VUV": 139.14860152,
    "WST": 3.17029742,
    "XAF": 655.957,
    "XCD": 3.18833358,
    "XCG": 2.11374708,
    "XDR": 0.85842046,
    "XOF": 655.957,
    "XPF": 119.332,
    "YER": 281.50747131,
    "ZAR": 18.8258267,
    "ZMW": 22.23348828,
    "ZWG": 30.44219996,
    "ZWL": 30.4422
  }
}

In [9]:
currencies = ['NOK', 'EUR', 'SEK', 'PLN', 'RON', 'DKK', 'CZK']

### Explaination : 

- 1 Eur = 10.83 Sek
- 1 Eur = 11.54 Nok

- 1 Nok = 1/11.54
- 1 Sek = 1/10.83 

- Base to Target = base_rate_currency / target_rate_currency

- Nok/Sek = 1 Nok = 1/11.54 / 1/10.83 OR 1/11.54 * 10.83 = xx Sek

In [20]:
from itertools import combinations, permutations
'''
Combinations if we want to have unique pairs
Permutations to have all pairs and facilitate queries for analysis
'''  

currencies = ['NOK', 'EUR', 'SEK', 'PLN', 'RON', 'DKK', 'CZK']

rates_vs_eur = {currency: data['conversion_rates'][currency] for currency in currencies}

cross_pairs = {}
for base, target in permutations(currencies, 2):
    pair = f"{base}/{target}"
    cross_pairs[pair] = rates_vs_eur[target] / rates_vs_eur[base]
    print(pair)
    print(f"{rates_vs_eur[target]} / {rates_vs_eur[base]}")

NOK/EUR
1 / 11.23618761
NOK/SEK
10.66776006 / 11.23618761
NOK/PLN
4.22446344 / 11.23618761
NOK/RON
5.09496799 / 11.23618761
NOK/DKK
7.46130519 / 11.23618761
NOK/CZK
24.24169306 / 11.23618761
EUR/NOK
11.23618761 / 1
EUR/SEK
10.66776006 / 1
EUR/PLN
4.22446344 / 1
EUR/RON
5.09496799 / 1
EUR/DKK
7.46130519 / 1
EUR/CZK
24.24169306 / 1
SEK/NOK
11.23618761 / 10.66776006
SEK/EUR
1 / 10.66776006
SEK/PLN
4.22446344 / 10.66776006
SEK/RON
5.09496799 / 10.66776006
SEK/DKK
7.46130519 / 10.66776006
SEK/CZK
24.24169306 / 10.66776006
PLN/NOK
11.23618761 / 4.22446344
PLN/EUR
1 / 4.22446344
PLN/SEK
10.66776006 / 4.22446344
PLN/RON
5.09496799 / 4.22446344
PLN/DKK
7.46130519 / 4.22446344
PLN/CZK
24.24169306 / 4.22446344
RON/NOK
11.23618761 / 5.09496799
RON/EUR
1 / 5.09496799
RON/SEK
10.66776006 / 5.09496799
RON/PLN
4.22446344 / 5.09496799
RON/DKK
7.46130519 / 5.09496799
RON/CZK
24.24169306 / 5.09496799
DKK/NOK
11.23618761 / 7.46130519
DKK/EUR
1 / 7.46130519
DKK/SEK
10.66776006 / 7.46130519
DKK/PLN
4.22446344 / 7.46130519
DKK/RON
5.09496799 / 7.46130519
DKK/CZK
24.24169306 / 7.46130519
CZK/NOK
11.23618761 / 24.24169306
CZK/EUR
1 / 24.24169306
CZK/SEK
10.66776006 / 24.24169306
CZK/PLN
4.22446344 / 24.24169306
CZK/RON
5.09496799 / 24.24169306
CZK/DKK
7.46130519 / 24.24169306

In [21]:
for pair, rate in cross_pairs.items():
    print(f"{pair}: {rate:.6f}")

NOK/EUR: 0.088998
NOK/SEK: 0.949411
NOK/PLN: 0.375969
NOK/RON: 0.453443
NOK/DKK: 0.664042
NOK/CZK: 2.157466
EUR/NOK: 11.236188
EUR/SEK: 10.667760
EUR/PLN: 4.224463
EUR/RON: 5.094968
EUR/DKK: 7.461305
EUR/CZK: 24.241693
SEK/NOK: 1.053285
SEK/EUR: 0.093740
SEK/PLN: 0.396003
SEK/RON: 0.477604
SEK/DKK: 0.699426
SEK/CZK: 2.272426
PLN/NOK: 2.659790
PLN/EUR: 0.236716
PLN/SEK: 2.525234
PLN/RON: 1.206063
PLN/DKK: 1.766214
PLN/CZK: 5.738408
RON/NOK: 2.205350
RON/EUR: 0.196272
RON/SEK: 2.093784
RON/PLN: 0.829144
RON/DKK: 1.464446
RON/CZK: 4.757968
DKK/NOK: 1.505928
DKK/EUR: 0.134025
DKK/SEK: 1.429745
DKK/PLN: 0.566183
DKK/RON: 0.682852
DKK/CZK: 3.248988
CZK/NOK: 0.463507
CZK/EUR: 0.041251
CZK/SEK: 0.440058
CZK/PLN: 0.174264
CZK/RON: 0.210174
CZK/DKK: 0.307788

In [23]:
len(cross_pairs)

42

### Pairs should be 42 : 

7 currencies with 6 variations : 7 * (7-1)/2 = 21 * 2(for duplicates EUR/NOK - NOK/EUR) = 42

### Fetch historical data

In [4]:
import os
import requests
import pandas as pd
from datetime import datetime, timedelta
from dotenv import load_dotenv

In [7]:
load_dotenv()

api_key = os.getenv("api_key")
# api_key

In [8]:
base_currency = "EUR"
target_currencies = ["NOK", "EUR", "SEK", "PLN", "RON", "DKK", "CZK"]

In [14]:
start_date = datetime(2026, 2, 26)
end_date = datetime.today()

In [33]:
records = []
current_date = start_date

In [34]:
current_date

datetime.datetime(2026, 2, 26, 0, 0)

In [29]:
start_date

datetime.datetime(2026, 2, 26, 0, 0)

In [67]:
while current_date < end_date:
    year    = current_date.year
    month   = current_date.month
    day     = current_date.day

    url = f"https://v6.exchangerate-api.com/v6/{api_key}/history/EUR/{year}/{month}/{day}"
    response = requests.get(url)
    data = response.json()

    try:
        rates = data["conversion_rates"]
        record = {"date" : current_date.strftime("%Y-%m-%d")}
        
        for currency in target_currencies:
            record[currency] = rates.get(currency) 
        
        records.append(record)

        current_date += timedelta(days=1)
    except Exception as e:
        print("ERROR : ", e)

In [68]:
records

[{'date': '2026-02-26',
  'NOK': 11.28407463,
  'EUR': 1,
  'SEK': 10.65796541,
  'PLN': 4.2181691,
  'RON': 5.09443304,
  'DKK': 7.46330265,
  'CZK': 24.22916733},
 {'date': '2026-02-27',
  'NOK': 11.27947743,
  'EUR': 1,
  'SEK': 10.67802938,
  'PLN': 4.22261816,
  'RON': 5.09501245,
  'DKK': 7.46346323,
  'CZK': 24.2493814},
 {'date': '2026-02-28',
  'NOK': 11.23775346,
  'EUR': 1,
  'SEK': 10.66789828,
  'PLN': 4.22473171,
  'RON': 5.09591778,
  'DKK': 7.46343647,
  'CZK': 24.24158178},
 {'date': '2026-03-01',
  'NOK': 11.23846859,
  'EUR': 1,
  'SEK': 10.66803924,
  'PLN': 4.2244742,
  'RON': 5.09489025,
  'DKK': 7.46085446,
  'CZK': 24.24152321}]

In [69]:
df = pd.DataFrame(records)
df

,date,NOK,EUR,SEK,PLN,RON,DKK,CZK
0,2026-02-26,11.284075,1,10.657965,4.218169,5.094433,7.463303,24.229167
1,2026-02-27,11.279477,1,10.678029,4.222618,5.095012,7.463463,24.249381
2,2026-02-28,11.237753,1,10.667898,4.224732,5.095918,7.463436,24.241582
3,2026-03-01,11.238469,1,10.668039,4.224474,5.094890,7.460854,24.241523

### Year To Date (YTD) : 
- From 1st jan to current date
- From today year-1 to current date ?

### Cross pairs

In [70]:
from itertools import permutations

In [71]:
currencies = ["NOK", "EUR", "SEK", "PLN", "RON", "DKK", "CZK"]

In [72]:
cross_pairs = []

In [73]:
for _, row in df.iterrows():
    for base, target in permutations(currencies, 2):
        rate = row[target] / row[base]
        cross_pairs.append({
            "date": row["date"],
            "base_currency": base,
            "target_currency": target,
            "rate": round(rate, 6)
        })

In [74]:
cross_pairs

[{'date': '2026-02-26',
  'base_currency': 'NOK',
  'target_currency': 'EUR',
  'rate': 0.08862},
 {'date': '2026-02-26',
  'base_currency': 'NOK',
  'target_currency': 'SEK',
  'rate': 0.944514},
 {'date': '2026-02-26',
  'base_currency': 'NOK',
  'target_currency': 'PLN',
  'rate': 0.373816},
 {'date': '2026-02-26',
  'base_currency': 'NOK',
  'target_currency': 'RON',
  'rate': 0.451471},
 {'date': '2026-02-26',
  'base_currency': 'NOK',
  'target_currency': 'DKK',
  'rate': 0.661401},
 {'date': '2026-02-26',
  'base_currency': 'NOK',
  'target_currency': 'CZK',
  'rate': 2.1472},
 {'date': '2026-02-26',
  'base_currency': 'EUR',
  'target_currency': 'NOK',
  'rate': 11.284075},
 {'date': '2026-02-26',
  'base_currency': 'EUR',
  'target_currency': 'SEK',
  'rate': 10.657965},
 {'date': '2026-02-26',
  'base_currency': 'EUR',
  'target_currency': 'PLN',
  'rate': 4.218169},
 {'date': '2026-02-26',
  'base_currency': 'EUR',
  'target_currency': 'RON',
  'rate': 5.094433},
 {'date': '2026-02-26',
  'base_currency': 'EUR',
  'target_currency': 'DKK',
  'rate': 7.463303},
 {'date': '2026-02-26',
  'base_currency': 'EUR',
  'target_currency': 'CZK',
  'rate': 24.229167},
 {'date': '2026-02-26',
  'base_currency': 'SEK',
  'target_currency': 'NOK',
  'rate': 1.058746},
 {'date': '2026-02-26',
  'base_currency': 'SEK',
  'target_currency': 'EUR',
  'rate': 0.093827},
 {'date': '2026-02-26',
  'base_currency': 'SEK',
  'target_currency': 'PLN',
  'rate': 0.395776},
 {'date': '2026-02-26',
  'base_currency': 'SEK',
  'target_currency': 'RON',
  'rate': 0.477993},
 {'date': '2026-02-26',
  'base_currency': 'SEK',
  'target_currency': 'DKK',
  'rate': 0.700256},
 {'date': '2026-02-26',
  'base_currency': 'SEK',
  'target_currency': 'CZK',
  'rate': 2.273339},
 {'date': '2026-02-26',
  'base_currency': 'PLN',
  'target_currency': 'NOK',
  'rate': 2.675112},
 {'date': '2026-02-26',
  'base_currency': 'PLN',
  'target_currency': 'EUR',
  'rate': 0.23707},
 {'date': '2026-02-26',
  'base_currency': 'PLN',
  'target_currency': 'SEK',
  'rate': 2.52668},
 {'date': '2026-02-26',
  'base_currency': 'PLN',
  'target_currency': 'RON',
  'rate': 1.207736},
 {'date': '2026-02-26',
  'base_currency': 'PLN',
  'target_currency': 'DKK',
  'rate': 1.769323},
 {'date': '2026-02-26',
  'base_currency': 'PLN',
  'target_currency': 'CZK',
  'rate': 5.744001},
 {'date': '2026-02-26',
  'base_currency': 'RON',
  'target_currency': 'NOK',
  'rate': 2.214981},
 {'date': '2026-02-26',
  'base_currency': 'RON',
  'target_currency': 'EUR',
  'rate': 0.196293},
 {'date': '2026-02-26',
  'base_currency': 'RON',
  'target_currency': 'SEK',
  'rate': 2.092081},
 {'date': '2026-02-26',
  'base_currency': 'RON',
  'target_currency': 'PLN',
  'rate': 0.827996},
 {'date': '2026-02-26',
  'base_currency': 'RON',
  'target_currency': 'DKK',
  'rate': 1.464992},
 {'date': '2026-02-26',
  'base_currency': 'RON',
  'target_currency': 'CZK',
  'rate': 4.756009},
 {'date': '2026-02-26',
  'base_currency': 'DKK',
  'target_currency': 'NOK',
  'rate': 1.511941},
 {'date': '2026-02-26',
  'base_currency': 'DKK',
  'target_currency': 'EUR',
  'rate': 0.133989},
 {'date': '2026-02-26',
  'base_currency': 'DKK',
  'target_currency': 'SEK',
  'rate': 1.428049},
 {'date': '2026-02-26',
  'base_currency': 'DKK',
  'target_currency': 'PLN',
  'rate': 0.565188},
 {'date': '2026-02-26',
  'base_currency': 'DKK',
  'target_currency': 'RON',
  'rate': 0.682598},
 {'date': '2026-02-26',
  'base_currency': 'DKK',
  'target_currency': 'CZK',
  'rate': 3.24644},
 {'date': '2026-02-26',
  'base_currency': 'CZK',
  'target_currency': 'NOK',
  'rate': 0.465723},
 {'date': '2026-02-26',
  'base_currency': 'CZK',
  'target_currency': 'EUR',
  'rate': 0.041273},
 {'date': '2026-02-26',
  'base_currency': 'CZK',
  'target_currency': 'SEK',
  'rate': 0.439882},
 {'date': '2026-02-26',
  'base_currency': 'CZK',
  'target_currency': 'PLN',
  'rate': 0.174095},
 {'date': '2026-02-26',
  'base_currency': 'CZK',
  'target_currency': 'RON',
  'rate': 0.21026},
 {'date': '2026-02-26',
  'base_currency': 'CZK',
  'target_currency': 'DKK',
  'rate': 0.30803},
 {'date': '2026-02-27',
  'base_currency': 'NOK',
  'target_currency': 'EUR',
  'rate': 0.088657},
 {'date': '2026-02-27',
  'base_currency': 'NOK',
  'target_currency': 'SEK',
  'rate': 0.946678},
 {'date': '2026-02-27',
  'base_currency': 'NOK',
  'target_currency': 'PLN',
  'rate': 0.374363},
 {'date': '2026-02-27',
  'base_currency': 'NOK',
  'target_currency': 'RON',
  'rate': 0.451706},
 {'date': '2026-02-27',
  'base_currency': 'NOK',
  'target_currency': 'DKK',
  'rate': 0.661685},
 {'date': '2026-02-27',
  'base_currency': 'NOK',
  'target_currency': 'CZK',
  'rate': 2.149867},
 {'date': '2026-02-27',
  'base_currency': 'EUR',
  'target_currency': 'NOK',
  'rate': 11.279477},
 {'date': '2026-02-27',
  'base_currency': 'EUR',
  'target_currency': 'SEK',
  'rate': 10.678029},
 {'date': '2026-02-27',
  'base_currency': 'EUR',
  'target_currency': 'PLN',
  'rate': 4.222618},
 {'date': '2026-02-27',
  'base_currency': 'EUR',
  'target_currency': 'RON',
  'rate': 5.095012},
 {'date': '2026-02-27',
  'base_currency': 'EUR',
  'target_currency': 'DKK',
  'rate': 7.463463},
 {'date': '2026-02-27',
  'base_currency': 'EUR',
  'target_currency': 'CZK',
  'rate': 24.249381},
 {'date': '2026-02-27',
  'base_currency': 'SEK',
  'target_currency': 'NOK',
  'rate': 1.056326},
 {'date': '2026-02-27',
  'base_currency': 'SEK',
  'target_currency': 'EUR',
  'rate': 0.09365},
 {'date': '2026-02-27',
  'base_currency': 'SEK',
  'target_currency': 'PLN',
  'rate': 0.395449},
 {'date': '2026-02-27',
  'base_currency': 'SEK',
  'target_currency': 'RON',
  'rate': 0.477149},
 {'date': '2026-02-27',
  'base_currency': 'SEK',
  'target_currency': 'DKK',
  'rate': 0.698955},
 {'date': '2026-02-27',
  'base_currency': 'SEK',
  'target_currency': 'CZK',
  'rate': 2.27096},
 {'date': '2026-02-27',
  'base_currency': 'PLN',
  'target_currency': 'NOK',
  'rate': 2.671205},
 {'date': '2026-02-27',
  'base_currency': 'PLN',
  'target_currency': 'EUR',
  'rate': 0.23682},
 {'date': '2026-02-27',
  'base_currency': 'PLN',
  'target_currency': 'SEK',
  'rate': 2.52877},
 {'date': '2026-02-27',
  'base_currency': 'PLN',
  'target_currency': 'RON',
  'rate': 1.2066},
 {'date': '2026-02-27',
  'base_currency': 'PLN',
  'target_currency': 'DKK',
  'rate': 1.767497},
 {'date': '2026-02-27',
  'base_currency': 'PLN',
  'target_currency': 'CZK',
  'rate': 5.742736},
 {'date': '2026-02-27',
  'base_currency': 'RON',
  'target_currency': 'NOK',
  'rate': 2.213827},
 {'date': '2026-02-27',
  'base_currency': 'RON',
  'target_currency': 'EUR',
  'rate': 0.19627},
 {'date': '2026-02-27',
  'base_currency': 'RON',
  'target_currency': 'SEK',
  'rate': 2.095781},
 {'date': '2026-02-27',
  'base_currency': 'RON',
  'target_currency': 'PLN',
  'rate': 0.828775},
 {'date': '2026-02-27',
  'base_currency': 'RON',
  'target_currency': 'DKK',
  'rate': 1.464857},
 {'date': '2026-02-27',
  'base_currency': 'RON',
  'target_currency': 'CZK',
  'rate': 4.759435},
 {'date': '2026-02-27',
  'base_currency': 'DKK',
  'target_currency': 'NOK',
  'rate': 1.511293},
 {'date': '2026-02-27',
  'base_currency': 'DKK',
  'target_currency': 'EUR',
  'rate': 0.133986},
 {'date': '2026-02-27',
  'base_currency': 'DKK',
  'target_currency': 'SEK',
  'rate': 1.430707},
 {'date': '2026-02-27',
  'base_currency': 'DKK',
  'target_currency': 'PLN',
  'rate': 0.565772},
 {'date': '2026-02-27',
  'base_currency': 'DKK',
  'target_currency': 'RON',
  'rate': 0.682661},
 {'date': '2026-02-27',
  'base_currency': 'DKK',
  'target_currency': 'CZK',
  'rate': 3.249079},
 {'date': '2026-02-27',
  'base_currency': 'CZK',
  'target_currency': 'NOK',
  'rate': 0.465145},
 {'date': '2026-02-27',
  'base_currency': 'CZK',
  'target_currency': 'EUR',
  'rate': 0.041238},
 {'date': '2026-02-27',
  'base_currency': 'CZK',
  'target_currency': 'SEK',
  'rate': 0.440342},
 {'date': '2026-02-27',
  'base_currency': 'CZK',
  'target_currency': 'PLN',
  'rate': 0.174133},
 {'date': '2026-02-27',
  'base_currency': 'CZK',
  'target_currency': 'RON',
  'rate': 0.210109},
 {'date': '2026-02-27',
  'base_currency': 'CZK',
  'target_currency': 'DKK',
  'rate': 0.30778},
 {'date': '2026-02-28',
  'base_currency': 'NOK',
  'target_currency': 'EUR',
  'rate': 0.088986},
 {'date': '2026-02-28',
  'base_currency': 'NOK',
  'target_currency': 'SEK',
  'rate': 0.949291},
 {'date': '2026-02-28',
  'base_currency': 'NOK',
  'target_currency': 'PLN',
  'rate': 0.375941},
 {'date': '2026-02-28',
  'base_currency': 'NOK',
  'target_currency': 'RON',
  'rate': 0.453464},
 {'date': '2026-02-28',
  'base_currency': 'NOK',
  'target_currency': 'DKK',
  'rate': 0.66414},
 {'date': '2026-02-28',
  'base_currency': 'NOK',
  'target_currency': 'CZK',
  'rate': 2.157156},
 {'date': '2026-02-28',
  'base_currency': 'EUR',
  'target_currency': 'NOK',
  'rate': 11.237753},
 {'date': '2026-02-28',
  'base_currency': 'EUR',
  'target_currency': 'SEK',
  'rate': 10.667898},
 {'date': '2026-02-28',
  'base_currency': 'EUR',
  'target_currency': 'PLN',
  'rate': 4.224732},
 {'date': '2026-02-28',
  'base_currency': 'EUR',
  'target_currency': 'RON',
  'rate': 5.095918},
 {'date': '2026-02-28',
  'base_currency': 'EUR',
  'target_currency': 'DKK',
  'rate': 7.463436},
 {'date': '2026-02-28',
  'base_currency': 'EUR',
  'target_currency': 'CZK',
  'rate': 24.241582},
 {'date': '2026-02-28',
  'base_currency': 'SEK',
  'target_currency': 'NOK',
  'rate': 1.053418},
 {'date': '2026-02-28',
  'base_currency': 'SEK',
  'target_currency': 'EUR',
  'rate': 0.093739},
 {'date': '2026-02-28',
  'base_currency': 'SEK',
  'target_currency': 'PLN',
  'rate': 0.396023},
 {'date': '2026-02-28',
  'base_currency': 'SEK',
  'target_currency': 'RON',
  'rate': 0.477687},
 {'date': '2026-02-28',
  'base_currency': 'SEK',
  'target_currency': 'DKK',
  'rate': 0.699616},
 {'date': '2026-02-28',
  'base_currency': 'SEK',
  'target_currency': 'CZK',
  'rate': 2.272386},
 {'date': '2026-02-28',
  'base_currency': 'PLN',
  'target_currency': 'NOK',
  'rate': 2.659992},
 {'date': '2026-02-28',
  'base_currency': 'PLN',
  'target_currency': 'EUR',
  'rate': 0.236701},
 {'date': '2026-02-28',
  'base_currency': 'PLN',
  'target_currency': 'SEK',
  'rate': 2.525107},
 {'date': '2026-02-28',
  'base_currency': 'PLN',
  'target_currency': 'RON',
  'rate': 1.206211},
 {'date': '2026-02-28',
  'base_currency': 'PLN',
  'target_currency': 'DKK',
  'rate': 1.766606},
 {'date': '2026-02-28',
  'base_currency': 'PLN',
  'target_currency': 'CZK',
  'rate': 5.738017},
 {'date': '2026-02-28',
  'base_currency': 'RON',
  'target_currency': 'NOK',
  'rate': 2.205246},
 {'date': '2026-02-28',
  'base_currency': 'RON',
  'target_currency': 'EUR',
  'rate': 0.196236},
 {'date': '2026-02-28',
  'base_currency': 'RON',
  'target_currency': 'SEK',
  'rate': 2.09342},
 {'date': '2026-02-28',
  'base_currency': 'RON',
  'target_currency': 'PLN',
  'rate': 0.829042},
 {'date': '2026-02-28',
  'base_currency': 'RON',
  'target_currency': 'DKK',
  'rate': 1.464591},
 {'date': '2026-02-28',
  'base_currency': 'RON',
  'target_currency': 'CZK',
  'rate': 4.757059},
 {'date': '2026-02-28',
  'base_currency': 'DKK',
  'target_currency': 'NOK',
  'rate': 1.505708},
 {'date': '2026-02-28',
  'base_currency': 'DKK',
  'target_currency': 'EUR',
  'rate': 0.133987},
 {'date': '2026-02-28',
  'base_currency': 'DKK',
  'target_currency': 'SEK',
  'rate': 1.429355},
 {'date': '2026-02-28',
  'base_currency': 'DKK',
  'target_currency': 'PLN',
  'rate': 0.566057},
 {'date': '2026-02-28',
  'base_currency': 'DKK',
  'target_currency': 'RON',
  'rate': 0.682784},
 {'date': '2026-02-28',
  'base_currency': 'DKK',
  'target_currency': 'CZK',
  'rate': 3.248046},
 {'date': '2026-02-28',
  'base_currency': 'CZK',
  'target_currency': 'NOK',
  'rate': 0.463573},
 {'date': '2026-02-28',
  'base_currency': 'CZK',
  'target_currency': 'EUR',
  'rate': 0.041251},
 {'date': '2026-02-28',
  'base_currency': 'CZK',
  'target_currency': 'SEK',
  'rate': 0.440066},
 {'date': '2026-02-28',
  'base_currency': 'CZK',
  'target_currency': 'PLN',
  'rate': 0.174276},
 {'date': '2026-02-28',
  'base_currency': 'CZK',
  'target_currency': 'RON',
  'rate': 0.210214},
 {'date': '2026-02-28',
  'base_currency': 'CZK',
  'target_currency': 'DKK',
  'rate': 0.307877},
 {'date': '2026-03-01',
  'base_currency': 'NOK',
  'target_currency': 'EUR',
  'rate': 0.08898},
 {'date': '2026-03-01',
  'base_currency': 'NOK',
  'target_currency': 'SEK',
  'rate': 0.949243},
 {'date': '2026-03-01',
  'base_currency': 'NOK',
  'target_currency': 'PLN',
  'rate': 0.375894},
 {'date': '2026-03-01',
  'base_currency': 'NOK',
  'target_currency': 'RON',
  'rate': 0.453344},
 {'date': '2026-03-01',
  'base_currency': 'NOK',
  'target_currency': 'DKK',
  'rate': 0.663868},
 {'date': '2026-03-01',
  'base_currency': 'NOK',
  'target_currency': 'CZK',
  'rate': 2.157013},
 {'date': '2026-03-01',
  'base_currency': 'EUR',
  'target_currency': 'NOK',
  'rate': 11.238469},
 {'date': '2026-03-01',
  'base_currency': 'EUR',
  'target_currency': 'SEK',
  'rate': 10.668039},
 {'date': '2026-03-01',
  'base_currency': 'EUR',
  'target_currency': 'PLN',
  'rate': 4.224474},
 {'date': '2026-03-01',
  'base_currency': 'EUR',
  'target_currency': 'RON',
  'rate': 5.09489},
 {'date': '2026-03-01',
  'base_currency': 'EUR',
  'target_currency': 'DKK',
  'rate': 7.460854},
 {'date': '2026-03-01',
  'base_currency': 'EUR',
  'target_currency': 'CZK',
  'rate': 24.241523},
 {'date': '2026-03-01',
  'base_currency': 'SEK',
  'target_currency': 'NOK',
  'rate': 1.053471},
 {'date': '2026-03-01',
  'base_currency': 'SEK',
  'target_currency': 'EUR',
  'rate': 0.093738},
 {'date': '2026-03-01',
  'base_currency': 'SEK',
  'target_currency': 'PLN',
  'rate': 0.395994},
 {'date': '2026-03-01',
  'base_currency': 'SEK',
  'target_currency': 'RON',
  'rate': 0.477585},
 {'date': '2026-03-01',
  'base_currency': 'SEK',
  'target_currency': 'DKK',
  'rate': 0.699365},
 {'date': '2026-03-01',
  'base_currency': 'SEK',
  'target_currency': 'CZK',
  'rate': 2.27235},
 {'date': '2026-03-01',
  'base_currency': 'PLN',
  'target_currency': 'NOK',
  'rate': 2.660324},
 {'date': '2026-03-01',
  'base_currency': 'PLN',
  'target_currency': 'EUR',
  'rate': 0.236716},
 {'date': '2026-03-01',
  'base_currency': 'PLN',
  'target_currency': 'SEK',
  'rate': 2.525294},
 {'date': '2026-03-01',
  'base_currency': 'PLN',
  'target_currency': 'RON',
  'rate': 1.206041},
 {'date': '2026-03-01',
  'base_currency': 'PLN',
  'target_currency': 'DKK',
  'rate': 1.766103},
 {'date': '2026-03-01',
  'base_currency': 'PLN',
  'target_currency': 'CZK',
  'rate': 5.738353},
 {'date': '2026-03-01',
  'base_currency': 'RON',
  'target_currency': 'NOK',
  'rate': 2.205831},
 {'date': '2026-03-01',
  'base_currency': 'RON',
  'target_currency': 'EUR',
  'rate': 0.196275},
 {'date': '2026-03-01',
  'base_currency': 'RON',
  'target_currency': 'SEK',
  'rate': 2.09387},
 {'date': '2026-03-01',
  'base_currency': 'RON',
  'target_currency': 'PLN',
  'rate': 0.829159},
 {'date': '2026-03-01',
  'base_currency': 'RON',
  'target_currency': 'DKK',
  'rate': 1.46438},
 {'date': '2026-03-01',
  'base_currency': 'RON',
  'target_currency': 'CZK',
  'rate': 4.758007},
 {'date': '2026-03-01',
  'base_currency': 'DKK',
  'target_currency': 'NOK',
  'rate': 1.506325},
 {'date': '2026-03-01',
  'base_currency': 'DKK',
  'target_currency': 'EUR',
  'rate': 0.134033},
 {'date': '2026-03-01',
  'base_currency': 'DKK',
  'target_currency': 'SEK',
  'rate': 1.429868},
 {'date': '2026-03-01',
  'base_currency': 'DKK',
  'target_currency': 'PLN',
  'rate': 0.566219},
 {'date': '2026-03-01',
  'base_currency': 'DKK',
  'target_currency': 'RON',
  'rate': 0.682883},
 {'date': '2026-03-01',
  'base_currency': 'DKK',
  'target_currency': 'CZK',
  'rate': 3.249162},
 {'date': '2026-03-01',
  'base_currency': 'CZK',
  'target_currency': 'NOK',
  'rate': 0.463604},
 {'date': '2026-03-01',
  'base_currency': 'CZK',
  'target_currency': 'EUR',
  'rate': 0.041252},
 {'date': '2026-03-01',
  'base_currency': 'CZK',
  'target_currency': 'SEK',
  'rate': 0.440073},
 {'date': '2026-03-01',
  'base_currency': 'CZK',
  'target_currency': 'PLN',
  'rate': 0.174266},
 {'date': '2026-03-01',
  'base_currency': 'CZK',
  'target_currency': 'RON',
  'rate': 0.210172},
 {'date': '2026-03-01',
  'base_currency': 'CZK',
  'target_currency': 'DKK',
  'rate': 0.307772}]

In [76]:
df_pairs = pd.DataFrame(cross_pairs)
df_pairs

           date base_currency target_currency      rate
0    2026-02-26           NOK             EUR  0.088620
1    2026-02-26           NOK             SEK  0.944514
2    2026-02-26           NOK             PLN  0.373816
3    2026-02-26           NOK             RON  0.451471
4    2026-02-26           NOK             DKK  0.661401
..          ...           ...             ...       ...
163  2026-03-01           CZK             EUR  0.041252
164  2026-03-01           CZK             SEK  0.440073
165  2026-03-01           CZK             PLN  0.174266
166  2026-03-01           CZK             RON  0.210172
167  2026-03-01           CZK             DKK  0.307772

[168 rows x 4 columns]

In [77]:
168 / 42

4.0

In [78]:
df['date'].value_counts()

date
2026-02-26    1
2026-02-27    1
2026-02-28    1
2026-03-01    1
Name: count, dtype: int64

In [79]:
df_pairs['date'].value_counts()

date
2026-02-26    42
2026-02-27    42
2026-02-28    42
2026-03-01    42
Name: count, dtype: int64

### Why long format (currencies in rows) and not wide format (currencies as columns):
- Scalability : Alter schema is simple : No need for DDL to modify schema. Eg: adding new curr : api call or calculations, more tricky, need to calculate every column CASE WHEN...
-  Easy joins : base curr and target curr,

## Dimensional table : dim currency

In [80]:
currencies

['NOK', 'EUR', 'SEK', 'PLN', 'RON', 'DKK', 'CZK']

In [84]:
dim = []

for currency in currencies:
    response = requests.get(f"https://v6.exchangerate-api.com/v6/{api_key}/enriched/EUR/{currency}")
    data = response.json()

    if data.get("result") == "success":
        dim.append({
            "locale" : data["target_data"]["locale"]
            , "two_letter_code" : data["target_data"]["two_letter_code"]
            , "currency_name" : data["target_data"]["currency_name"]
            , "currency_name_short" : data["target_data"]["currency_name_short"]
        })
    else:
        print(data.get("result"))

In [86]:
dim

[{'locale': 'Norway',
  'two_letter_code': 'NO',
  'currency_name': 'Norwegian Krone',
  'currency_name_short': 'Krone'},
 {'locale': 'European Union',
  'two_letter_code': 'EU',
  'currency_name': 'Euro',
  'currency_name_short': 'Euro'},
 {'locale': 'Sweden',
  'two_letter_code': 'SE',
  'currency_name': 'Swedish Krona',
  'currency_name_short': 'Krona'},
 {'locale': 'Poland',
  'two_letter_code': 'PL',
  'currency_name': 'Polish Złoty',
  'currency_name_short': 'Złoty'},
 {'locale': 'Romania',
  'two_letter_code': 'RO',
  'currency_name': 'Romanian Leu',
  'currency_name_short': 'Leu'},
 {'locale': 'Denmark',
  'two_letter_code': 'DK',
  'currency_name': 'Danish Krone',
  'currency_name_short': 'Krone'},
 {'locale': 'Czech Republic',
  'two_letter_code': 'CZ',
  'currency_name': 'Czech Koruna',
  'currency_name_short': 'Koruna'}]

In [87]:
df_dim = pd.DataFrame(dim)
df_dim

           locale two_letter_code    currency_name currency_name_short
0          Norway              NO  Norwegian Krone               Krone
1  European Union              EU             Euro                Euro
2          Sweden              SE    Swedish Krona               Krona
3          Poland              PL     Polish Złoty               Złoty
4         Romania              RO     Romanian Leu                 Leu
5         Denmark              DK     Danish Krone               Krone
6  Czech Republic              CZ     Czech Koruna              Koruna

### Schema DDL Data Definiton Language : 
- Dim Date   : date, year, fiscal_year, month, quarter, fiscal_quarter 
- Dim Curr   : locale, two_letter_code, currency_name, currency_name_short
- Fact Rates : base_curr, target_curr

In [88]:
import sqlite3

In [89]:
db_path = "fx_warehouse.sqlite"

In [93]:
conn = sqlite3.connect(db_path)
conn

In [94]:
cursor = conn.cursor()

### Create Dimension tables: Currency and Date

In [95]:
df_dim

           locale two_letter_code    currency_name currency_name_short
0          Norway              NO  Norwegian Krone               Krone
1  European Union              EU             Euro                Euro
2          Sweden              SE    Swedish Krona               Krona
3          Poland              PL     Polish Złoty               Złoty
4         Romania              RO     Romanian Leu                 Leu
5         Denmark              DK     Danish Krone               Krone
6  Czech Republic              CZ     Czech Koruna              Koruna

In [96]:
df_pairs

           date base_currency target_currency      rate
0    2026-02-26           NOK             EUR  0.088620
1    2026-02-26           NOK             SEK  0.944514
2    2026-02-26           NOK             PLN  0.373816
3    2026-02-26           NOK             RON  0.451471
4    2026-02-26           NOK             DKK  0.661401
..          ...           ...             ...       ...
163  2026-03-01           CZK             EUR  0.041252
164  2026-03-01           CZK             SEK  0.440073
165  2026-03-01           CZK             PLN  0.174266
166  2026-03-01           CZK             RON  0.210172
167  2026-03-01           CZK             DKK  0.307772

[168 rows x 4 columns]

#### Date dim

In [109]:
from datetime import datetime, timedelta

In [119]:
date_records = []
current = datetime(2025, 1, 1)
end = datetime.today()

In [127]:
cursor.execute("""
    CREATE TABLE IF NOT EXISTS dim_date(
        date TEXT PRIMARY KEY
        , year INTEGER NOT NULL
        , month INTEGER NOT NULL
        , day INTEGER NOT NULL
        , quarter INTEGER NOT NULL
    );
""")

In [ ]:
while current < end:
    date_records.append((
        current
        , current.year
        , current.month
        , current.day
        , (current.month - 1) // 3 + 1
    ))

    current += timedelta(days=1)

In [129]:
date_records[:3]

[(datetime.datetime(2025, 1, 1, 0, 0), 2025, 1, 1, 1),
 (datetime.datetime(2025, 1, 2, 0, 0), 2025, 1, 2, 1),
 (datetime.datetime(2025, 1, 3, 0, 0), 2025, 1, 3, 1)]

In [131]:
cursor.executemany("""
    INSERT INTO dim_date(date, year, month, day, quarter)
    VALUES(?, ?, ?, ?, ?)
""", date_records)

/tmp/ipykernel_395983/4057788049.py:1: DeprecationWarning: The default datetime adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  cursor.executemany("""