In [9]:
import os
import json
import requests
from dotenv import load_dotenv

In [10]:
load_dotenv()

api_key = os.getenv("api_key")

In [12]:
load_dotenv()

url = f'https://v6.exchangerate-api.com/v6/{api_key}/latest/EUR'

response = requests.get(url)
data = response.json()

In [13]:
print(data)

{'result': 'success', 'documentation': 'https://www.exchangerate-api.com/docs', 'terms_of_use': 'https://www.exchangerate-api.com/terms', 'time_last_update_unix': 1772398802, 'time_last_update_utc': 'Sun, 01 Mar 2026 21:00:02 +0000', 'time_next_update_unix': 1772402402, 'time_next_update_utc': 'Sun, 01 Mar 2026 22:00:02 +0000', 'base_code': 'EUR', 'conversion_rates': {'EUR': 1, 'AED': 4.3277788, 'AFN': 74.75860313, 'ALL': 96.25595346, 'AMD': 445.40306859, 'ANG': 2.10938708, 'AOA': 1093.52665027, 'ARS': 1711.37284083, 'AUD': 1.66549486, 'AWG': 2.10938708, 'AZN': 2.00784572, 'BAM': 1.95583, 'BBD': 2.35685707, 'BDT': 144.33829705, 'BGN': 1.95583, 'BHD': 0.44308913, 'BIF': 3505.98865914, 'BMD': 1.17842854, 'BND': 1.49391645, 'BOB': 8.17490373, 'BRL': 6.06918813, 'BSD': 1.17842854, 'BTN': 107.51924901, 'BWP': 15.98279336, 'BYN': 3.40068762, 'BZD': 2.35685707, 'CAD': 1.60910711, 'CDF': 2693.41791045, 'CHF': 0.9059116, 'CLF': 0.02598802, 'CLP': 1027.25338189, 'CNH': 8.09883275, 'CNY': 8.08125598, 'COP': 4398.05693413, 'CRC': 558.58544719, 'CUP': 28.28228485, 'CVE': 110.265, 'CZK': 24.24255538, 'DJF': 209.43149778, 'DKK': 7.46083908, 'DOP': 70.60149198, 'DZD': 153.48572587, 'EGP': 56.63589502, 'ERN': 17.67642803, 'ETB': 184.40450181, 'FJD': 2.57418133, 'FKP': 0.87614074, 'FOK': 7.46083905, 'GBP': 0.87626048, 'GEL': 3.1583682, 'GGP': 0.87614074, 'GHS': 12.62230484, 'GIP': 0.87614074, 'GMD': 87.60128188, 'GNF': 10316.87038433, 'GTQ': 9.05846576, 'GYD': 247.20410959, 'HKD': 9.21741846, 'HNL': 31.25883953, 'HRK': 7.5345, 'HTG': 154.9669386, 'HUF': 376.47929425, 'IDR': 19836.83896902, 'ILS': 3.69763499, 'IMP': 0.87614074, 'INR': 107.51934756, 'IQD': 1549.00429185, 'IRR': 1549079.88412009, 'ISK': 143.45858115, 'JEP': 0.87614074, 'JMD': 184.38938175, 'JOD': 0.83550583, 'JPY': 183.88112091, 'KES': 152.35576841, 'KGS': 103.30330763, 'KHR': 4748.92105263, 'KID': 1.6651015, 'KMF': 491.96775, 'KRW': 1702.28401933, 'KWD': 0.36104653, 'KYD': 0.98202339, 'KZT': 588.71379125, 'LAK': 25720.71500982, 'LBP': 105469.35393634, 'LKR': 364.37831482, 'LRD': 216.75274998, 'LSL': 18.88232198, 'LYD': 7.46129993, 'MAD': 10.80914099, 'MDL': 20.1260567, 'MGA': 4944.06807089, 'MKD': 61.6948, 'MMK': 2487.96429077, 'MNT': 4184.52465278, 'MOP': 9.49216753, 'MRU': 47.3148925, 'MUR': 54.68650178, 'MVR': 18.26158613, 'MWK': 2052.81852401, 'MXN': 20.38537078, 'MYR': 4.59517659, 'MZN': 75.55682259, 'NAD': 18.88232198, 'NGN': 1599.14562768, 'NIO': 43.45924211, 'NOK': 11.21742644, 'NPR': 172.03079842, 'NZD': 1.97341347, 'OMR': 0.45310224, 'PAB': 1.17842854, 'PEN': 3.9629113, 'PGK': 5.14540601, 'PHP': 68.1540011, 'PKR': 330.38630829, 'PLN': 4.22468543, 'PYG': 7667.64768056, 'QAR': 4.28947987, 'RON': 5.09490219, 'RSD': 117.45122636, 'RUB': 91.32515416, 'RWF': 1720.06705314, 'SAR': 4.41910701, 'SBD': 9.29847539, 'SCR': 16.55805215, 'SDG': 528.43045388, 'SEK': 10.66851598, 'SGD': 1.4939172, 'SHP': 0.87614074, 'SLE': 28.84812942, 'SLL': 28848.23854747, 'SOS': 674.61308411, 'SRD': 44.64044527, 'SSP': 5414.00038168, 'STN': 24.5, 'SYP': 135.87603033, 'SZL': 18.88232198, 'THB': 36.68469217, 'TJS': 11.08250613, 'TMT': 4.13312443, 'TND': 3.38044622, 'TOP': 2.74744398, 'TRY': 51.78950638, 'TTD': 8.60348582, 'TVD': 1.6651015, 'TWD': 37.06021319, 'TZS': 3016.86267936, 'UAH': 50.93754607, 'UGX': 4227.42149069, 'USD': 1.17858471, 'UYU': 45.40690638, 'UZS': 14414.69411932, 'VES': 495.60601336, 'VND': 30457.73749569, 'VUV': 138.59240474, 'WST': 3.13575042, 'XAF': 655.957, 'XCD': 3.18175705, 'XCG': 2.10938708, 'XDR': 0.85842039, 'XOF': 655.957, 'XPF': 119.332, 'YER': 281.49797662, 'ZAR': 18.88551489, 'ZMW': 22.22841983, 'ZWG': 30.44219996, 'ZWL': 30.4422}}

In [14]:
print(json.dumps(data, indent=2))

{
  "result": "success",
  "documentation": "https://www.exchangerate-api.com/docs",
  "terms_of_use": "https://www.exchangerate-api.com/terms",
  "time_last_update_unix": 1772398802,
  "time_last_update_utc": "Sun, 01 Mar 2026 21:00:02 +0000",
  "time_next_update_unix": 1772402402,
  "time_next_update_utc": "Sun, 01 Mar 2026 22:00:02 +0000",
  "base_code": "EUR",
  "conversion_rates": {
    "EUR": 1,
    "AED": 4.3277788,
    "AFN": 74.75860313,
    "ALL": 96.25595346,
    "AMD": 445.40306859,
    "ANG": 2.10938708,
    "AOA": 1093.52665027,
    "ARS": 1711.37284083,
    "AUD": 1.66549486,
    "AWG": 2.10938708,
    "AZN": 2.00784572,
    "BAM": 1.95583,
    "BBD": 2.35685707,
    "BDT": 144.33829705,
    "BGN": 1.95583,
    "BHD": 0.44308913,
    "BIF": 3505.98865914,
    "BMD": 1.17842854,
    "BND": 1.49391645,
    "BOB": 8.17490373,
    "BRL": 6.06918813,
    "BSD": 1.17842854,
    "BTN": 107.51924901,
    "BWP": 15.98279336,
    "BYN": 3.40068762,
    "BZD": 2.35685707,
    "CAD": 1.60910711,
    "CDF": 2693.41791045,
    "CHF": 0.9059116,
    "CLF": 0.02598802,
    "CLP": 1027.25338189,
    "CNH": 8.09883275,
    "CNY": 8.08125598,
    "COP": 4398.05693413,
    "CRC": 558.58544719,
    "CUP": 28.28228485,
    "CVE": 110.265,
    "CZK": 24.24255538,
    "DJF": 209.43149778,
    "DKK": 7.46083908,
    "DOP": 70.60149198,
    "DZD": 153.48572587,
    "EGP": 56.63589502,
    "ERN": 17.67642803,
    "ETB": 184.40450181,
    "FJD": 2.57418133,
    "FKP": 0.87614074,
    "FOK": 7.46083905,
    "GBP": 0.87626048,
    "GEL": 3.1583682,
    "GGP": 0.87614074,
    "GHS": 12.62230484,
    "GIP": 0.87614074,
    "GMD": 87.60128188,
    "GNF": 10316.87038433,
    "GTQ": 9.05846576,
    "GYD": 247.20410959,
    "HKD": 9.21741846,
    "HNL": 31.25883953,
    "HRK": 7.5345,
    "HTG": 154.9669386,
    "HUF": 376.47929425,
    "IDR": 19836.83896902,
    "ILS": 3.69763499,
    "IMP": 0.87614074,
    "INR": 107.51934756,
    "IQD": 1549.00429185,
    "IRR": 1549079.88412009,
    "ISK": 143.45858115,
    "JEP": 0.87614074,
    "JMD": 184.38938175,
    "JOD": 0.83550583,
    "JPY": 183.88112091,
    "KES": 152.35576841,
    "KGS": 103.30330763,
    "KHR": 4748.92105263,
    "KID": 1.6651015,
    "KMF": 491.96775,
    "KRW": 1702.28401933,
    "KWD": 0.36104653,
    "KYD": 0.98202339,
    "KZT": 588.71379125,
    "LAK": 25720.71500982,
    "LBP": 105469.35393634,
    "LKR": 364.37831482,
    "LRD": 216.75274998,
    "LSL": 18.88232198,
    "LYD": 7.46129993,
    "MAD": 10.80914099,
    "MDL": 20.1260567,
    "MGA": 4944.06807089,
    "MKD": 61.6948,
    "MMK": 2487.96429077,
    "MNT": 4184.52465278,
    "MOP": 9.49216753,
    "MRU": 47.3148925,
    "MUR": 54.68650178,
    "MVR": 18.26158613,
    "MWK": 2052.81852401,
    "MXN": 20.38537078,
    "MYR": 4.59517659,
    "MZN": 75.55682259,
    "NAD": 18.88232198,
    "NGN": 1599.14562768,
    "NIO": 43.45924211,
    "NOK": 11.21742644,
    "NPR": 172.03079842,
    "NZD": 1.97341347,
    "OMR": 0.45310224,
    "PAB": 1.17842854,
    "PEN": 3.9629113,
    "PGK": 5.14540601,
    "PHP": 68.1540011,
    "PKR": 330.38630829,
    "PLN": 4.22468543,
    "PYG": 7667.64768056,
    "QAR": 4.28947987,
    "RON": 5.09490219,
    "RSD": 117.45122636,
    "RUB": 91.32515416,
    "RWF": 1720.06705314,
    "SAR": 4.41910701,
    "SBD": 9.29847539,
    "SCR": 16.55805215,
    "SDG": 528.43045388,
    "SEK": 10.66851598,
    "SGD": 1.4939172,
    "SHP": 0.87614074,
    "SLE": 28.84812942,
    "SLL": 28848.23854747,
    "SOS": 674.61308411,
    "SRD": 44.64044527,
    "SSP": 5414.00038168,
    "STN": 24.5,
    "SYP": 135.87603033,
    "SZL": 18.88232198,
    "THB": 36.68469217,
    "TJS": 11.08250613,
    "TMT": 4.13312443,
    "TND": 3.38044622,
    "TOP": 2.74744398,
    "TRY": 51.78950638,
    "TTD": 8.60348582,
    "TVD": 1.6651015,
    "TWD": 37.06021319,
    "TZS": 3016.86267936,
    "UAH": 50.93754607,
    "UGX": 4227.42149069,
    "USD": 1.17858471,
    "UYU": 45.40690638,
    "UZS": 14414.69411932,
    "VES": 495.60601336,
    "VND": 30457.73749569,
    "VUV": 138.59240474,
    "WST": 3.13575042,
    "XAF": 655.957,
    "XCD": 3.18175705,
    "XCG": 2.10938708,
    "XDR": 0.85842039,
    "XOF": 655.957,
    "XPF": 119.332,
    "YER": 281.49797662,
    "ZAR": 18.88551489,
    "ZMW": 22.22841983,
    "ZWG": 30.44219996,
    "ZWL": 30.4422
  }
}

In [15]:
currencies = ['NOK', 'EUR', 'SEK', 'PLN', 'RON', 'DKK', 'CZK']

### Explaination : 

- 1 Eur = 10.83 Sek
- 1 Eur = 11.54 Nok

- 1 Nok = 1/11.54
- 1 Sek = 1/10.83 

- Base to Target = base_rate_currency / target_rate_currency

- Nok/Sek = 1 Nok = 1/11.54 / 1/10.83 OR 1/11.54 * 10.83 = xx Sek

In [16]:
from itertools import combinations, permutations
'''
Combinations if we want to have unique pairs
Permutations to have all pairs and facilitate queries for analysis
'''  

currencies = ['NOK', 'EUR', 'SEK', 'PLN', 'RON', 'DKK', 'CZK']

rates_vs_eur = {currency: data['conversion_rates'][currency] for currency in currencies}

cross_pairs = {}
for base, target in permutations(currencies, 2):
    pair = f"{base}/{target}"
    cross_pairs[pair] = rates_vs_eur[target] / rates_vs_eur[base]
    print(pair)
    print(f"{rates_vs_eur[target]} / {rates_vs_eur[base]}")

NOK/EUR
1 / 11.21742644
NOK/SEK
10.66851598 / 11.21742644
NOK/PLN
4.22468543 / 11.21742644
NOK/RON
5.09490219 / 11.21742644
NOK/DKK
7.46083908 / 11.21742644
NOK/CZK
24.24255538 / 11.21742644
EUR/NOK
11.21742644 / 1
EUR/SEK
10.66851598 / 1
EUR/PLN
4.22468543 / 1
EUR/RON
5.09490219 / 1
EUR/DKK
7.46083908 / 1
EUR/CZK
24.24255538 / 1
SEK/NOK
11.21742644 / 10.66851598
SEK/EUR
1 / 10.66851598
SEK/PLN
4.22468543 / 10.66851598
SEK/RON
5.09490219 / 10.66851598
SEK/DKK
7.46083908 / 10.66851598
SEK/CZK
24.24255538 / 10.66851598
PLN/NOK
11.21742644 / 4.22468543
PLN/EUR
1 / 4.22468543
PLN/SEK
10.66851598 / 4.22468543
PLN/RON
5.09490219 / 4.22468543
PLN/DKK
7.46083908 / 4.22468543
PLN/CZK
24.24255538 / 4.22468543
RON/NOK
11.21742644 / 5.09490219
RON/EUR
1 / 5.09490219
RON/SEK
10.66851598 / 5.09490219
RON/PLN
4.22468543 / 5.09490219
RON/DKK
7.46083908 / 5.09490219
RON/CZK
24.24255538 / 5.09490219
DKK/NOK
11.21742644 / 7.46083908
DKK/EUR
1 / 7.46083908
DKK/SEK
10.66851598 / 7.46083908
DKK/PLN
4.22468543 / 7.46083908
DKK/RON
5.09490219 / 7.46083908
DKK/CZK
24.24255538 / 7.46083908
CZK/NOK
11.21742644 / 24.24255538
CZK/EUR
1 / 24.24255538
CZK/SEK
10.66851598 / 24.24255538
CZK/PLN
4.22468543 / 24.24255538
CZK/RON
5.09490219 / 24.24255538
CZK/DKK
7.46083908 / 24.24255538

In [17]:
for pair, rate in cross_pairs.items():
    print(f"{pair}: {rate:.6f}")

NOK/EUR: 0.089147
NOK/SEK: 0.951066
NOK/PLN: 0.376618
NOK/RON: 0.454195
NOK/DKK: 0.665111
NOK/CZK: 2.161151
EUR/NOK: 11.217426
EUR/SEK: 10.668516
EUR/PLN: 4.224685
EUR/RON: 5.094902
EUR/DKK: 7.460839
EUR/CZK: 24.242555
SEK/NOK: 1.051451
SEK/EUR: 0.093734
SEK/PLN: 0.395996
SEK/RON: 0.477564
SEK/DKK: 0.699332
SEK/CZK: 2.272346
PLN/NOK: 2.655210
PLN/EUR: 0.236704
PLN/SEK: 2.525281
PLN/RON: 1.205984
PLN/DKK: 1.766011
PLN/CZK: 5.738310
RON/NOK: 2.201696
RON/EUR: 0.196275
RON/SEK: 2.093959
RON/PLN: 0.829199
RON/DKK: 1.464373
RON/CZK: 4.758198
DKK/NOK: 1.503507
DKK/EUR: 0.134033
DKK/SEK: 1.429935
DKK/PLN: 0.566248
DKK/RON: 0.682886
DKK/CZK: 3.249307
CZK/NOK: 0.462716
CZK/EUR: 0.041250
CZK/SEK: 0.440074
CZK/PLN: 0.174267
CZK/RON: 0.210164
CZK/DKK: 0.307758

In [18]:
len(cross_pairs)

42

### Pairs should be 42 : 

7 currencies with 6 variations : 7 * (7-1)/2 = 21 * 2(for duplicates EUR/NOK - NOK/EUR) = 42

### Fetch historical data

In [19]:
import os
import requests
import pandas as pd
from datetime import datetime, timedelta
from dotenv import load_dotenv

In [20]:
load_dotenv()

api_key = os.getenv("api_key")
# api_key

In [21]:
base_currency = "EUR"
target_currencies = ["NOK", "EUR", "SEK", "PLN", "RON", "DKK", "CZK"]

In [22]:
start_date = datetime(2026, 2, 26)
end_date = datetime.today()

In [23]:
records = []
current_date = start_date

In [24]:
current_date

datetime.datetime(2026, 2, 26, 0, 0)

In [25]:
start_date

datetime.datetime(2026, 2, 26, 0, 0)

In [26]:
while current_date < end_date:
    year    = current_date.year
    month   = current_date.month
    day     = current_date.day

    url = f"https://v6.exchangerate-api.com/v6/{api_key}/history/EUR/{year}/{month}/{day}"
    response = requests.get(url)
    data = response.json()

    try:
        rates = data["conversion_rates"]
        record = {"date" : current_date.strftime("%Y-%m-%d")}
        
        for currency in target_currencies:
            record[currency] = rates.get(currency) 
        
        records.append(record)

        current_date += timedelta(days=1)
    except Exception as e:
        print("ERROR : ", e)

In [27]:
records

[{'date': '2026-02-26',
  'NOK': 11.28407463,
  'EUR': 1,
  'SEK': 10.65796541,
  'PLN': 4.2181691,
  'RON': 5.09443304,
  'DKK': 7.46330265,
  'CZK': 24.22916733},
 {'date': '2026-02-27',
  'NOK': 11.27947743,
  'EUR': 1,
  'SEK': 10.67802938,
  'PLN': 4.22261816,
  'RON': 5.09501245,
  'DKK': 7.46346323,
  'CZK': 24.2493814},
 {'date': '2026-02-28',
  'NOK': 11.23775346,
  'EUR': 1,
  'SEK': 10.66789828,
  'PLN': 4.22473171,
  'RON': 5.09591778,
  'DKK': 7.46343647,
  'CZK': 24.24158178},
 {'date': '2026-03-01',
  'NOK': 11.21742644,
  'EUR': 1,
  'SEK': 10.66851598,
  'PLN': 4.22468543,
  'RON': 5.09490219,
  'DKK': 7.46083908,
  'CZK': 24.24255538}]

In [28]:
df = pd.DataFrame(records)
df

,date,NOK,EUR,SEK,PLN,RON,DKK,CZK
0,2026-02-26,11.284075,1,10.657965,4.218169,5.094433,7.463303,24.229167
1,2026-02-27,11.279477,1,10.678029,4.222618,5.095012,7.463463,24.249381
2,2026-02-28,11.237753,1,10.667898,4.224732,5.095918,7.463436,24.241582
3,2026-03-01,11.217426,1,10.668516,4.224685,5.094902,7.460839,24.242555

### Cross pairs

In [29]:
from itertools import permutations

In [30]:
currencies = ["NOK", "EUR", "SEK", "PLN", "RON", "DKK", "CZK"]

In [31]:
cross_pairs = []

In [32]:
for _, row in df.iterrows():
    for base, target in permutations(currencies, 2):
        rate = row[target] / row[base]
        cross_pairs.append({
            "date": row["date"],
            "base_currency": base,
            "target_currency": target,
            "rate": round(rate, 6)
        })

In [33]:
cross_pairs

[{'date': '2026-02-26',
  'base_currency': 'NOK',
  'target_currency': 'EUR',
  'rate': 0.08862},
 {'date': '2026-02-26',
  'base_currency': 'NOK',
  'target_currency': 'SEK',
  'rate': 0.944514},
 {'date': '2026-02-26',
  'base_currency': 'NOK',
  'target_currency': 'PLN',
  'rate': 0.373816},
 {'date': '2026-02-26',
  'base_currency': 'NOK',
  'target_currency': 'RON',
  'rate': 0.451471},
 {'date': '2026-02-26',
  'base_currency': 'NOK',
  'target_currency': 'DKK',
  'rate': 0.661401},
 {'date': '2026-02-26',
  'base_currency': 'NOK',
  'target_currency': 'CZK',
  'rate': 2.1472},
 {'date': '2026-02-26',
  'base_currency': 'EUR',
  'target_currency': 'NOK',
  'rate': 11.284075},
 {'date': '2026-02-26',
  'base_currency': 'EUR',
  'target_currency': 'SEK',
  'rate': 10.657965},
 {'date': '2026-02-26',
  'base_currency': 'EUR',
  'target_currency': 'PLN',
  'rate': 4.218169},
 {'date': '2026-02-26',
  'base_currency': 'EUR',
  'target_currency': 'RON',
  'rate': 5.094433},
 {'date': '2026-02-26',
  'base_currency': 'EUR',
  'target_currency': 'DKK',
  'rate': 7.463303},
 {'date': '2026-02-26',
  'base_currency': 'EUR',
  'target_currency': 'CZK',
  'rate': 24.229167},
 {'date': '2026-02-26',
  'base_currency': 'SEK',
  'target_currency': 'NOK',
  'rate': 1.058746},
 {'date': '2026-02-26',
  'base_currency': 'SEK',
  'target_currency': 'EUR',
  'rate': 0.093827},
 {'date': '2026-02-26',
  'base_currency': 'SEK',
  'target_currency': 'PLN',
  'rate': 0.395776},
 {'date': '2026-02-26',
  'base_currency': 'SEK',
  'target_currency': 'RON',
  'rate': 0.477993},
 {'date': '2026-02-26',
  'base_currency': 'SEK',
  'target_currency': 'DKK',
  'rate': 0.700256},
 {'date': '2026-02-26',
  'base_currency': 'SEK',
  'target_currency': 'CZK',
  'rate': 2.273339},
 {'date': '2026-02-26',
  'base_currency': 'PLN',
  'target_currency': 'NOK',
  'rate': 2.675112},
 {'date': '2026-02-26',
  'base_currency': 'PLN',
  'target_currency': 'EUR',
  'rate': 0.23707},
 {'date': '2026-02-26',
  'base_currency': 'PLN',
  'target_currency': 'SEK',
  'rate': 2.52668},
 {'date': '2026-02-26',
  'base_currency': 'PLN',
  'target_currency': 'RON',
  'rate': 1.207736},
 {'date': '2026-02-26',
  'base_currency': 'PLN',
  'target_currency': 'DKK',
  'rate': 1.769323},
 {'date': '2026-02-26',
  'base_currency': 'PLN',
  'target_currency': 'CZK',
  'rate': 5.744001},
 {'date': '2026-02-26',
  'base_currency': 'RON',
  'target_currency': 'NOK',
  'rate': 2.214981},
 {'date': '2026-02-26',
  'base_currency': 'RON',
  'target_currency': 'EUR',
  'rate': 0.196293},
 {'date': '2026-02-26',
  'base_currency': 'RON',
  'target_currency': 'SEK',
  'rate': 2.092081},
 {'date': '2026-02-26',
  'base_currency': 'RON',
  'target_currency': 'PLN',
  'rate': 0.827996},
 {'date': '2026-02-26',
  'base_currency': 'RON',
  'target_currency': 'DKK',
  'rate': 1.464992},
 {'date': '2026-02-26',
  'base_currency': 'RON',
  'target_currency': 'CZK',
  'rate': 4.756009},
 {'date': '2026-02-26',
  'base_currency': 'DKK',
  'target_currency': 'NOK',
  'rate': 1.511941},
 {'date': '2026-02-26',
  'base_currency': 'DKK',
  'target_currency': 'EUR',
  'rate': 0.133989},
 {'date': '2026-02-26',
  'base_currency': 'DKK',
  'target_currency': 'SEK',
  'rate': 1.428049},
 {'date': '2026-02-26',
  'base_currency': 'DKK',
  'target_currency': 'PLN',
  'rate': 0.565188},
 {'date': '2026-02-26',
  'base_currency': 'DKK',
  'target_currency': 'RON',
  'rate': 0.682598},
 {'date': '2026-02-26',
  'base_currency': 'DKK',
  'target_currency': 'CZK',
  'rate': 3.24644},
 {'date': '2026-02-26',
  'base_currency': 'CZK',
  'target_currency': 'NOK',
  'rate': 0.465723},
 {'date': '2026-02-26',
  'base_currency': 'CZK',
  'target_currency': 'EUR',
  'rate': 0.041273},
 {'date': '2026-02-26',
  'base_currency': 'CZK',
  'target_currency': 'SEK',
  'rate': 0.439882},
 {'date': '2026-02-26',
  'base_currency': 'CZK',
  'target_currency': 'PLN',
  'rate': 0.174095},
 {'date': '2026-02-26',
  'base_currency': 'CZK',
  'target_currency': 'RON',
  'rate': 0.21026},
 {'date': '2026-02-26',
  'base_currency': 'CZK',
  'target_currency': 'DKK',
  'rate': 0.30803},
 {'date': '2026-02-27',
  'base_currency': 'NOK',
  'target_currency': 'EUR',
  'rate': 0.088657},
 {'date': '2026-02-27',
  'base_currency': 'NOK',
  'target_currency': 'SEK',
  'rate': 0.946678},
 {'date': '2026-02-27',
  'base_currency': 'NOK',
  'target_currency': 'PLN',
  'rate': 0.374363},
 {'date': '2026-02-27',
  'base_currency': 'NOK',
  'target_currency': 'RON',
  'rate': 0.451706},
 {'date': '2026-02-27',
  'base_currency': 'NOK',
  'target_currency': 'DKK',
  'rate': 0.661685},
 {'date': '2026-02-27',
  'base_currency': 'NOK',
  'target_currency': 'CZK',
  'rate': 2.149867},
 {'date': '2026-02-27',
  'base_currency': 'EUR',
  'target_currency': 'NOK',
  'rate': 11.279477},
 {'date': '2026-02-27',
  'base_currency': 'EUR',
  'target_currency': 'SEK',
  'rate': 10.678029},
 {'date': '2026-02-27',
  'base_currency': 'EUR',
  'target_currency': 'PLN',
  'rate': 4.222618},
 {'date': '2026-02-27',
  'base_currency': 'EUR',
  'target_currency': 'RON',
  'rate': 5.095012},
 {'date': '2026-02-27',
  'base_currency': 'EUR',
  'target_currency': 'DKK',
  'rate': 7.463463},
 {'date': '2026-02-27',
  'base_currency': 'EUR',
  'target_currency': 'CZK',
  'rate': 24.249381},
 {'date': '2026-02-27',
  'base_currency': 'SEK',
  'target_currency': 'NOK',
  'rate': 1.056326},
 {'date': '2026-02-27',
  'base_currency': 'SEK',
  'target_currency': 'EUR',
  'rate': 0.09365},
 {'date': '2026-02-27',
  'base_currency': 'SEK',
  'target_currency': 'PLN',
  'rate': 0.395449},
 {'date': '2026-02-27',
  'base_currency': 'SEK',
  'target_currency': 'RON',
  'rate': 0.477149},
 {'date': '2026-02-27',
  'base_currency': 'SEK',
  'target_currency': 'DKK',
  'rate': 0.698955},
 {'date': '2026-02-27',
  'base_currency': 'SEK',
  'target_currency': 'CZK',
  'rate': 2.27096},
 {'date': '2026-02-27',
  'base_currency': 'PLN',
  'target_currency': 'NOK',
  'rate': 2.671205},
 {'date': '2026-02-27',
  'base_currency': 'PLN',
  'target_currency': 'EUR',
  'rate': 0.23682},
 {'date': '2026-02-27',
  'base_currency': 'PLN',
  'target_currency': 'SEK',
  'rate': 2.52877},
 {'date': '2026-02-27',
  'base_currency': 'PLN',
  'target_currency': 'RON',
  'rate': 1.2066},
 {'date': '2026-02-27',
  'base_currency': 'PLN',
  'target_currency': 'DKK',
  'rate': 1.767497},
 {'date': '2026-02-27',
  'base_currency': 'PLN',
  'target_currency': 'CZK',
  'rate': 5.742736},
 {'date': '2026-02-27',
  'base_currency': 'RON',
  'target_currency': 'NOK',
  'rate': 2.213827},
 {'date': '2026-02-27',
  'base_currency': 'RON',
  'target_currency': 'EUR',
  'rate': 0.19627},
 {'date': '2026-02-27',
  'base_currency': 'RON',
  'target_currency': 'SEK',
  'rate': 2.095781},
 {'date': '2026-02-27',
  'base_currency': 'RON',
  'target_currency': 'PLN',
  'rate': 0.828775},
 {'date': '2026-02-27',
  'base_currency': 'RON',
  'target_currency': 'DKK',
  'rate': 1.464857},
 {'date': '2026-02-27',
  'base_currency': 'RON',
  'target_currency': 'CZK',
  'rate': 4.759435},
 {'date': '2026-02-27',
  'base_currency': 'DKK',
  'target_currency': 'NOK',
  'rate': 1.511293},
 {'date': '2026-02-27',
  'base_currency': 'DKK',
  'target_currency': 'EUR',
  'rate': 0.133986},
 {'date': '2026-02-27',
  'base_currency': 'DKK',
  'target_currency': 'SEK',
  'rate': 1.430707},
 {'date': '2026-02-27',
  'base_currency': 'DKK',
  'target_currency': 'PLN',
  'rate': 0.565772},
 {'date': '2026-02-27',
  'base_currency': 'DKK',
  'target_currency': 'RON',
  'rate': 0.682661},
 {'date': '2026-02-27',
  'base_currency': 'DKK',
  'target_currency': 'CZK',
  'rate': 3.249079},
 {'date': '2026-02-27',
  'base_currency': 'CZK',
  'target_currency': 'NOK',
  'rate': 0.465145},
 {'date': '2026-02-27',
  'base_currency': 'CZK',
  'target_currency': 'EUR',
  'rate': 0.041238},
 {'date': '2026-02-27',
  'base_currency': 'CZK',
  'target_currency': 'SEK',
  'rate': 0.440342},
 {'date': '2026-02-27',
  'base_currency': 'CZK',
  'target_currency': 'PLN',
  'rate': 0.174133},
 {'date': '2026-02-27',
  'base_currency': 'CZK',
  'target_currency': 'RON',
  'rate': 0.210109},
 {'date': '2026-02-27',
  'base_currency': 'CZK',
  'target_currency': 'DKK',
  'rate': 0.30778},
 {'date': '2026-02-28',
  'base_currency': 'NOK',
  'target_currency': 'EUR',
  'rate': 0.088986},
 {'date': '2026-02-28',
  'base_currency': 'NOK',
  'target_currency': 'SEK',
  'rate': 0.949291},
 {'date': '2026-02-28',
  'base_currency': 'NOK',
  'target_currency': 'PLN',
  'rate': 0.375941},
 {'date': '2026-02-28',
  'base_currency': 'NOK',
  'target_currency': 'RON',
  'rate': 0.453464},
 {'date': '2026-02-28',
  'base_currency': 'NOK',
  'target_currency': 'DKK',
  'rate': 0.66414},
 {'date': '2026-02-28',
  'base_currency': 'NOK',
  'target_currency': 'CZK',
  'rate': 2.157156},
 {'date': '2026-02-28',
  'base_currency': 'EUR',
  'target_currency': 'NOK',
  'rate': 11.237753},
 {'date': '2026-02-28',
  'base_currency': 'EUR',
  'target_currency': 'SEK',
  'rate': 10.667898},
 {'date': '2026-02-28',
  'base_currency': 'EUR',
  'target_currency': 'PLN',
  'rate': 4.224732},
 {'date': '2026-02-28',
  'base_currency': 'EUR',
  'target_currency': 'RON',
  'rate': 5.095918},
 {'date': '2026-02-28',
  'base_currency': 'EUR',
  'target_currency': 'DKK',
  'rate': 7.463436},
 {'date': '2026-02-28',
  'base_currency': 'EUR',
  'target_currency': 'CZK',
  'rate': 24.241582},
 {'date': '2026-02-28',
  'base_currency': 'SEK',
  'target_currency': 'NOK',
  'rate': 1.053418},
 {'date': '2026-02-28',
  'base_currency': 'SEK',
  'target_currency': 'EUR',
  'rate': 0.093739},
 {'date': '2026-02-28',
  'base_currency': 'SEK',
  'target_currency': 'PLN',
  'rate': 0.396023},
 {'date': '2026-02-28',
  'base_currency': 'SEK',
  'target_currency': 'RON',
  'rate': 0.477687},
 {'date': '2026-02-28',
  'base_currency': 'SEK',
  'target_currency': 'DKK',
  'rate': 0.699616},
 {'date': '2026-02-28',
  'base_currency': 'SEK',
  'target_currency': 'CZK',
  'rate': 2.272386},
 {'date': '2026-02-28',
  'base_currency': 'PLN',
  'target_currency': 'NOK',
  'rate': 2.659992},
 {'date': '2026-02-28',
  'base_currency': 'PLN',
  'target_currency': 'EUR',
  'rate': 0.236701},
 {'date': '2026-02-28',
  'base_currency': 'PLN',
  'target_currency': 'SEK',
  'rate': 2.525107},
 {'date': '2026-02-28',
  'base_currency': 'PLN',
  'target_currency': 'RON',
  'rate': 1.206211},
 {'date': '2026-02-28',
  'base_currency': 'PLN',
  'target_currency': 'DKK',
  'rate': 1.766606},
 {'date': '2026-02-28',
  'base_currency': 'PLN',
  'target_currency': 'CZK',
  'rate': 5.738017},
 {'date': '2026-02-28',
  'base_currency': 'RON',
  'target_currency': 'NOK',
  'rate': 2.205246},
 {'date': '2026-02-28',
  'base_currency': 'RON',
  'target_currency': 'EUR',
  'rate': 0.196236},
 {'date': '2026-02-28',
  'base_currency': 'RON',
  'target_currency': 'SEK',
  'rate': 2.09342},
 {'date': '2026-02-28',
  'base_currency': 'RON',
  'target_currency': 'PLN',
  'rate': 0.829042},
 {'date': '2026-02-28',
  'base_currency': 'RON',
  'target_currency': 'DKK',
  'rate': 1.464591},
 {'date': '2026-02-28',
  'base_currency': 'RON',
  'target_currency': 'CZK',
  'rate': 4.757059},
 {'date': '2026-02-28',
  'base_currency': 'DKK',
  'target_currency': 'NOK',
  'rate': 1.505708},
 {'date': '2026-02-28',
  'base_currency': 'DKK',
  'target_currency': 'EUR',
  'rate': 0.133987},
 {'date': '2026-02-28',
  'base_currency': 'DKK',
  'target_currency': 'SEK',
  'rate': 1.429355},
 {'date': '2026-02-28',
  'base_currency': 'DKK',
  'target_currency': 'PLN',
  'rate': 0.566057},
 {'date': '2026-02-28',
  'base_currency': 'DKK',
  'target_currency': 'RON',
  'rate': 0.682784},
 {'date': '2026-02-28',
  'base_currency': 'DKK',
  'target_currency': 'CZK',
  'rate': 3.248046},
 {'date': '2026-02-28',
  'base_currency': 'CZK',
  'target_currency': 'NOK',
  'rate': 0.463573},
 {'date': '2026-02-28',
  'base_currency': 'CZK',
  'target_currency': 'EUR',
  'rate': 0.041251},
 {'date': '2026-02-28',
  'base_currency': 'CZK',
  'target_currency': 'SEK',
  'rate': 0.440066},
 {'date': '2026-02-28',
  'base_currency': 'CZK',
  'target_currency': 'PLN',
  'rate': 0.174276},
 {'date': '2026-02-28',
  'base_currency': 'CZK',
  'target_currency': 'RON',
  'rate': 0.210214},
 {'date': '2026-02-28',
  'base_currency': 'CZK',
  'target_currency': 'DKK',
  'rate': 0.307877},
 {'date': '2026-03-01',
  'base_currency': 'NOK',
  'target_currency': 'EUR',
  'rate': 0.089147},
 {'date': '2026-03-01',
  'base_currency': 'NOK',
  'target_currency': 'SEK',
  'rate': 0.951066},
 {'date': '2026-03-01',
  'base_currency': 'NOK',
  'target_currency': 'PLN',
  'rate': 0.376618},
 {'date': '2026-03-01',
  'base_currency': 'NOK',
  'target_currency': 'RON',
  'rate': 0.454195},
 {'date': '2026-03-01',
  'base_currency': 'NOK',
  'target_currency': 'DKK',
  'rate': 0.665111},
 {'date': '2026-03-01',
  'base_currency': 'NOK',
  'target_currency': 'CZK',
  'rate': 2.161151},
 {'date': '2026-03-01',
  'base_currency': 'EUR',
  'target_currency': 'NOK',
  'rate': 11.217426},
 {'date': '2026-03-01',
  'base_currency': 'EUR',
  'target_currency': 'SEK',
  'rate': 10.668516},
 {'date': '2026-03-01',
  'base_currency': 'EUR',
  'target_currency': 'PLN',
  'rate': 4.224685},
 {'date': '2026-03-01',
  'base_currency': 'EUR',
  'target_currency': 'RON',
  'rate': 5.094902},
 {'date': '2026-03-01',
  'base_currency': 'EUR',
  'target_currency': 'DKK',
  'rate': 7.460839},
 {'date': '2026-03-01',
  'base_currency': 'EUR',
  'target_currency': 'CZK',
  'rate': 24.242555},
 {'date': '2026-03-01',
  'base_currency': 'SEK',
  'target_currency': 'NOK',
  'rate': 1.051451},
 {'date': '2026-03-01',
  'base_currency': 'SEK',
  'target_currency': 'EUR',
  'rate': 0.093734},
 {'date': '2026-03-01',
  'base_currency': 'SEK',
  'target_currency': 'PLN',
  'rate': 0.395996},
 {'date': '2026-03-01',
  'base_currency': 'SEK',
  'target_currency': 'RON',
  'rate': 0.477564},
 {'date': '2026-03-01',
  'base_currency': 'SEK',
  'target_currency': 'DKK',
  'rate': 0.699332},
 {'date': '2026-03-01',
  'base_currency': 'SEK',
  'target_currency': 'CZK',
  'rate': 2.272346},
 {'date': '2026-03-01',
  'base_currency': 'PLN',
  'target_currency': 'NOK',
  'rate': 2.65521},
 {'date': '2026-03-01',
  'base_currency': 'PLN',
  'target_currency': 'EUR',
  'rate': 0.236704},
 {'date': '2026-03-01',
  'base_currency': 'PLN',
  'target_currency': 'SEK',
  'rate': 2.525281},
 {'date': '2026-03-01',
  'base_currency': 'PLN',
  'target_currency': 'RON',
  'rate': 1.205984},
 {'date': '2026-03-01',
  'base_currency': 'PLN',
  'target_currency': 'DKK',
  'rate': 1.766011},
 {'date': '2026-03-01',
  'base_currency': 'PLN',
  'target_currency': 'CZK',
  'rate': 5.73831},
 {'date': '2026-03-01',
  'base_currency': 'RON',
  'target_currency': 'NOK',
  'rate': 2.201696},
 {'date': '2026-03-01',
  'base_currency': 'RON',
  'target_currency': 'EUR',
  'rate': 0.196275},
 {'date': '2026-03-01',
  'base_currency': 'RON',
  'target_currency': 'SEK',
  'rate': 2.093959},
 {'date': '2026-03-01',
  'base_currency': 'RON',
  'target_currency': 'PLN',
  'rate': 0.829199},
 {'date': '2026-03-01',
  'base_currency': 'RON',
  'target_currency': 'DKK',
  'rate': 1.464373},
 {'date': '2026-03-01',
  'base_currency': 'RON',
  'target_currency': 'CZK',
  'rate': 4.758198},
 {'date': '2026-03-01',
  'base_currency': 'DKK',
  'target_currency': 'NOK',
  'rate': 1.503507},
 {'date': '2026-03-01',
  'base_currency': 'DKK',
  'target_currency': 'EUR',
  'rate': 0.134033},
 {'date': '2026-03-01',
  'base_currency': 'DKK',
  'target_currency': 'SEK',
  'rate': 1.429935},
 {'date': '2026-03-01',
  'base_currency': 'DKK',
  'target_currency': 'PLN',
  'rate': 0.566248},
 {'date': '2026-03-01',
  'base_currency': 'DKK',
  'target_currency': 'RON',
  'rate': 0.682886},
 {'date': '2026-03-01',
  'base_currency': 'DKK',
  'target_currency': 'CZK',
  'rate': 3.249307},
 {'date': '2026-03-01',
  'base_currency': 'CZK',
  'target_currency': 'NOK',
  'rate': 0.462716},
 {'date': '2026-03-01',
  'base_currency': 'CZK',
  'target_currency': 'EUR',
  'rate': 0.04125},
 {'date': '2026-03-01',
  'base_currency': 'CZK',
  'target_currency': 'SEK',
  'rate': 0.440074},
 {'date': '2026-03-01',
  'base_currency': 'CZK',
  'target_currency': 'PLN',
  'rate': 0.174267},
 {'date': '2026-03-01',
  'base_currency': 'CZK',
  'target_currency': 'RON',
  'rate': 0.210164},
 {'date': '2026-03-01',
  'base_currency': 'CZK',
  'target_currency': 'DKK',
  'rate': 0.307758}]

In [34]:
df_pairs = pd.DataFrame(cross_pairs)
df_pairs

           date base_currency target_currency      rate
0    2026-02-26           NOK             EUR  0.088620
1    2026-02-26           NOK             SEK  0.944514
2    2026-02-26           NOK             PLN  0.373816
3    2026-02-26           NOK             RON  0.451471
4    2026-02-26           NOK             DKK  0.661401
..          ...           ...             ...       ...
163  2026-03-01           CZK             EUR  0.041250
164  2026-03-01           CZK             SEK  0.440074
165  2026-03-01           CZK             PLN  0.174267
166  2026-03-01           CZK             RON  0.210164
167  2026-03-01           CZK             DKK  0.307758

[168 rows x 4 columns]

In [35]:
168 / 42

4.0

In [36]:
df['date'].value_counts()

date
2026-02-26    1
2026-02-27    1
2026-02-28    1
2026-03-01    1
Name: count, dtype: int64

In [37]:
df_pairs['date'].value_counts()

date
2026-02-26    42
2026-02-27    42
2026-02-28    42
2026-03-01    42
Name: count, dtype: int64

### Why long format (currencies in rows) and not wide format (currencies as columns):
- Scalability : Alter schema is simple : No need for DDL to modify schema. Eg: adding new curr : api call or calculations, more tricky, need to calculate every column CASE WHEN...
-  Easy joins : base curr and target curr,

## Dimensional table : dim currency

In [38]:
currencies

['NOK', 'EUR', 'SEK', 'PLN', 'RON', 'DKK', 'CZK']

In [56]:
dim = []

for currency in currencies:
    response = requests.get(f"https://v6.exchangerate-api.com/v6/{api_key}/enriched/EUR/{currency}")
    data = response.json()

    if data.get("result") == "success":
        dim.append({
            "currency": data["target_code"]
            , "locale" : data["target_data"]["locale"]
            , "two_letter_code" : data["target_data"]["two_letter_code"]
            , "currency_name" : data["target_data"]["currency_name"]
            , "currency_name_short" : data["target_data"]["currency_name_short"]
        })
    else:
        print(data.get("result"))

In [57]:
dim

[{'currency': 'NOK',
  'locale': 'Norway',
  'two_letter_code': 'NO',
  'currency_name': 'Norwegian Krone',
  'currency_name_short': 'Krone'},
 {'currency': 'EUR',
  'locale': 'European Union',
  'two_letter_code': 'EU',
  'currency_name': 'Euro',
  'currency_name_short': 'Euro'},
 {'currency': 'SEK',
  'locale': 'Sweden',
  'two_letter_code': 'SE',
  'currency_name': 'Swedish Krona',
  'currency_name_short': 'Krona'},
 {'currency': 'PLN',
  'locale': 'Poland',
  'two_letter_code': 'PL',
  'currency_name': 'Polish Złoty',
  'currency_name_short': 'Złoty'},
 {'currency': 'RON',
  'locale': 'Romania',
  'two_letter_code': 'RO',
  'currency_name': 'Romanian Leu',
  'currency_name_short': 'Leu'},
 {'currency': 'DKK',
  'locale': 'Denmark',
  'two_letter_code': 'DK',
  'currency_name': 'Danish Krone',
  'currency_name_short': 'Krone'},
 {'currency': 'CZK',
  'locale': 'Czech Republic',
  'two_letter_code': 'CZ',
  'currency_name': 'Czech Koruna',
  'currency_name_short': 'Koruna'}]

In [58]:
df_dim = pd.DataFrame(dim)
df_dim

,currency,locale,two_letter_code,currency_name,currency_name_short
0,NOK,Norway,NO,Norwegian Krone,Krone
1,EUR,European Union,EU,Euro,Euro
2,SEK,Sweden,SE,Swedish Krona,Krona
3,PLN,Poland,PL,Polish Złoty,Złoty
4,RON,Romania,RO,Romanian Leu,Leu
5,DKK,Denmark,DK,Danish Krone,Krone
6,CZK,Czech Republic,CZ,Czech Koruna,Koruna

### Schema DDL Data Definiton Language : 
- Dim Date   : date, year, fiscal_year, month, quarter, fiscal_quarter 
- Dim Curr   : locale, two_letter_code, currency_name, currency_name_short
- Fact Rates : base_curr, target_curr

In [205]:
import sqlite3

In [206]:
db_path = "fx_warehouse.sqlite"

In [207]:
conn = sqlite3.connect(db_path)
conn

In [208]:
cursor = conn.cursor()

### Create Dimension tables: Currency and Date

In [59]:
df_dim

,currency,locale,two_letter_code,currency_name,currency_name_short
0,NOK,Norway,NO,Norwegian Krone,Krone
1,EUR,European Union,EU,Euro,Euro
2,SEK,Sweden,SE,Swedish Krona,Krona
3,PLN,Poland,PL,Polish Złoty,Złoty
4,RON,Romania,RO,Romanian Leu,Leu
5,DKK,Denmark,DK,Danish Krone,Krone
6,CZK,Czech Republic,CZ,Czech Koruna,Koruna

In [47]:
df_pairs

           date base_currency target_currency      rate
0    2026-02-26           NOK             EUR  0.088620
1    2026-02-26           NOK             SEK  0.944514
2    2026-02-26           NOK             PLN  0.373816
3    2026-02-26           NOK             RON  0.451471
4    2026-02-26           NOK             DKK  0.661401
..          ...           ...             ...       ...
163  2026-03-01           CZK             EUR  0.041250
164  2026-03-01           CZK             SEK  0.440074
165  2026-03-01           CZK             PLN  0.174267
166  2026-03-01           CZK             RON  0.210164
167  2026-03-01           CZK             DKK  0.307758

[168 rows x 4 columns]

#### Date dim

In [210]:
from datetime import datetime, timedelta

In [ ]:
date_records = []
current = datetime(2026, 1, 1)
end = datetime.today()

In [95]:
# cursor.execute("""
#     DROP TABLE dim_date
# """)

In [212]:
cursor.execute("""
    CREATE TABLE IF NOT EXISTS dim_date(
        date TEXT PRIMARY KEY
        , year INTEGER NOT NULL
        , fiscal_year INTEGER NOT NULL
        , month INTEGER NOT NULL
        , day INTEGER NOT NULL
        , quarter INTEGER NOT NULL
    );
""")

In [213]:
while current < end:
    fiscal_year = current.year + 1 if current.month >= 10 else current.year 
    date_records.append((
        current.strftime("%Y-%m-%d")
        , current.year
        , fiscal_year
        , current.month
        , current.day
        , (current.month - 1) // 3 + 1
    ))

    current += timedelta(days=1)

In [214]:
date_records[:3]

[('2025-01-01', 2025, 2025, 1, 1, 1),
 ('2025-01-02', 2025, 2025, 1, 2, 1),
 ('2025-01-03', 2025, 2025, 1, 3, 1)]

In [215]:
cursor.executemany("""
    INSERT INTO dim_date(date, year, fiscal_year, month, day, quarter)
    VALUES(?, ?, ?, ?, ?, ?)
""", date_records)

In [216]:
conn.commit()

#### Dim currencies

In [217]:
df_dim

,currency,locale,two_letter_code,currency_name,currency_name_short
0,NOK,Norway,NO,Norwegian Krone,Krone
1,EUR,European Union,EU,Euro,Euro
2,SEK,Sweden,SE,Swedish Krona,Krona
3,PLN,Poland,PL,Polish Złoty,Złoty
4,RON,Romania,RO,Romanian Leu,Leu
5,DKK,Denmark,DK,Danish Krone,Krone
6,CZK,Czech Republic,CZ,Czech Koruna,Koruna

In [218]:
cursor.execute("""
    CREATE TABLE IF NOT EXISTS dim_currencies(
            currency TEXT PRIMARY KEY
            , locale TEXT NOT NULL
            , two_letter_code TEXT NOT NULL
            , currency_name TEXT NOT NULL
            , currency_name_short TEXT NOT NULL
        );
""")

In [219]:
df_dim

,currency,locale,two_letter_code,currency_name,currency_name_short
0,NOK,Norway,NO,Norwegian Krone,Krone
1,EUR,European Union,EU,Euro,Euro
2,SEK,Sweden,SE,Swedish Krona,Krona
3,PLN,Poland,PL,Polish Złoty,Złoty
4,RON,Romania,RO,Romanian Leu,Leu
5,DKK,Denmark,DK,Danish Krone,Krone
6,CZK,Czech Republic,CZ,Czech Koruna,Koruna

In [220]:
df_dim.to_sql("dim_currencies", conn, if_exists="append", index=False)

7

### Fact Foreign Exchange Rates

In [221]:
df_pairs.to_sql("fact_fx_rates", conn, if_exists="replace", index=False)

168

### QUERIES

In [ ]:
cursor.execute("""
    SELECT
        *
    FROM fact_fx_rates AS fx
    LEFT JOIN dim_date AS dd ON fx.date = dd.date
""").fetchall()

In [105]:
cursor.execute("""
    SELECT
        fx.*
        , dd.year
        , dd.month
        , dd.quarter
        , dc.*
    FROM fact_fx_rates AS fx
    LEFT JOIN dim_date AS dd ON fx.date = dd.date
    LEFT JOIN dim_currencies dc ON fx.base_currency = dc.currency
               
    WHERE fx.date = '2026-03-01'
    AND   fx.base_currency = 'NOK'
    AND   fx.target_currency = 'EUR'
""").fetchall()

[('2026-03-01',
  'NOK',
  'EUR',
  0.089147,
  2026,
  3,
  1,
  'NOK',
  'Norway',
  'NO',
  'Norwegian Krone',
  'Krone')]

In [107]:
pd.read_sql("""
    SELECT
        fx.*
        , dd.year
        , dd.month
        , dd.quarter
        , dc.*
    FROM fact_fx_rates AS fx
    LEFT JOIN dim_date AS dd ON fx.date = dd.date
    LEFT JOIN dim_currencies dc ON fx.base_currency = dc.currency
               
    WHERE fx.date = '2026-03-01'
    AND   fx.base_currency = 'NOK'
    AND   fx.target_currency = 'EUR'
""", conn)

,date,base_currency,target_currency,rate,year,month,quarter,currency,locale,two_letter_code,currency_name,currency_name_short
0,2026-03-01,NOK,EUR,0.089147,2026,3,1,NOK,Norway,NO,Norwegian Krone,Krone

### Year To Date (YTD) : 
- From 1st jan to current date
- Percentage Change = (current_date - 1st jan) / 1st jan * 100 
- Rates accumulation

In [108]:
df_pairs

           date base_currency target_currency      rate
0    2026-02-26           NOK             EUR  0.088620
1    2026-02-26           NOK             SEK  0.944514
2    2026-02-26           NOK             PLN  0.373816
3    2026-02-26           NOK             RON  0.451471
4    2026-02-26           NOK             DKK  0.661401
..          ...           ...             ...       ...
163  2026-03-01           CZK             EUR  0.041250
164  2026-03-01           CZK             SEK  0.440074
165  2026-03-01           CZK             PLN  0.174267
166  2026-03-01           CZK             RON  0.210164
167  2026-03-01           CZK             DKK  0.307758

[168 rows x 4 columns]

In [161]:
pd.read_sql("""
    WITH SUB AS(
        SELECT
            *
            , ROW_NUMBER() OVER(PARTITION BY base_currency, target_currency ORDER BY rate DESC) Max_Rate_RN
            , AVG(rate) OVER(PARTITION BY base_currency, target_currency) AS avg_rate
            , MAX(CASE WHEN date = '2026-02-26' THEN rate END) OVER(PARTITION BY base_currency, target_currency) AS jan_1st_rate
            , ROW_NUMBER() OVER(PARTITION BY base_currency, target_currency ORDER BY DATE DESC) AS last_date_RN
        FROM fact_fx_rates
        -- WHERE date >= '2026-01-01'
    )
            
    SELECT
        *
    FROM SUB
    --WHERE MAX_RATE_RN = 1
    WHERE base_currency = 'EUR'
    AND target_currency = 'NOK'
""", conn)

,date,base_currency,target_currency,rate,Max_Rate_RN,avg_rate,jan_1st_rate,last_date_RN
0,2026-02-26,EUR,NOK,11.284075,1,11.254683,11.284075,4
1,2026-02-27,EUR,NOK,11.279477,2,11.254683,11.284075,3
2,2026-02-28,EUR,NOK,11.237753,3,11.254683,11.284075,2
3,2026-03-01,EUR,NOK,11.217426,4,11.254683,11.284075,1

In [233]:
ytd_query = """
    WITH first_rate AS(
        SELECT
            base_currency	
            , target_currency
            , date AS first_date
            , rate AS first_rate	
        FROM fact_fx_rates 
        WHERE date = (SELECT MIN(DATE) FROM fact_fx_rates WHERE strftime('%Y', date) = strftime('%Y', 'now')) 
    ), 

    last_rate AS(
        SELECT
            base_currency	
            , target_currency
            , date AS last_date
            , rate AS last_rate
        FROM fact_fx_rates 
        WHERE date = (SELECT MAX(DATE) FROM fact_fx_rates WHERE strftime('%Y', date) = strftime('%Y', 'now'))	
    ),
    
    all_rates AS(
        SELECT
            base_currency	
            , target_currency
            , MIN(rate) AS min_rate
            , MAX(rate) AS max_rate
            , AVG(rate) AS avg_rate
        FROM fact_fx_rates
        WHERE strftime('%Y', date) = strftime('%Y', 'now')
        GROUP BY base_currency	
            , target_currency
    ) 

    SELECT
        FR.*
        , LR.last_date
        , LR.last_rate
        , AR.min_rate
        , AR.max_rate
        , AR.avg_rate
        , ROUND((LR.last_rate - FR.first_rate) / FR.first_rate * 100, 2) AS YTD_change_pct 
    FROM first_rate AS FR
    LEFT JOIN last_rate AS LR 
        ON  FR.base_currency = LR.base_currency
        AND FR.target_currency = LR.target_currency

    LEFT JOIN all_rates AS AR
        ON  FR.base_currency = AR.base_currency
        AND FR.target_currency = AR.target_currency
"""

In [192]:
df_pairs[(df_pairs['base_currency'] == 'NOK') & (df_pairs['target_currency'] == 'EUR')]

           date base_currency target_currency      rate
0    2026-02-26           NOK             EUR  0.088620
42   2026-02-27           NOK             EUR  0.088657
84   2026-02-28           NOK             EUR  0.088986
126  2026-03-01           NOK             EUR  0.089147

In [234]:
pd.read_sql(ytd_query, conn)

,base_currency,target_currency,first_date,first_rate,last_date,last_rate,min_rate,max_rate,avg_rate,YTD_change_pct
0,NOK,EUR,2026-02-26,0.088620,2026-03-01,0.089147,0.088620,0.089147,0.088853,0.59
1,NOK,SEK,2026-02-26,0.944514,2026-03-01,0.951066,0.944514,0.951066,0.947887,0.69
2,NOK,PLN,2026-02-26,0.373816,2026-03-01,0.376618,0.373816,0.376618,0.375185,0.75
3,NOK,RON,2026-02-26,0.451471,2026-03-01,0.454195,0.451471,0.454195,0.452709,0.60
4,NOK,DKK,2026-02-26,0.661401,2026-03-01,0.665111,0.661401,0.665111,0.663084,0.56
5,NOK,CZK,2026-02-26,2.147200,2026-03-01,2.161151,2.147200,2.161151,2.153843,0.65
6,EUR,NOK,2026-02-26,11.284075,2026-03-01,11.217426,11.217426,11.284075,11.254683,-0.59
7,EUR,SEK,2026-02-26,10.657965,2026-03-01,10.668516,10.657965,10.678029,10.668102,0.10
8,EUR,PLN,2026-02-26,4.218169,2026-03-01,4.224685,4.218169,4.224732,4.222551,0.15
9,EUR,RON,2026-02-26,5.094433,2026-03-01,5.094902,5.094433,5.095918,5.095066,0.01
10,EUR,DKK,2026-02-26,7.463303,2026-03-01,7.460839,7.460839,7.463463,7.462760,-0.03
11,EUR,CZK,2026-02-26,24.229167,2026-03-01,24.242555,24.229167,24.249381,24.240671,0.06
12,SEK,NOK,2026-02-26,1.058746,2026-03-01,1.051451,1.051451,1.058746,1.054985,-0.69
13,SEK,EUR,2026-02-26,0.093827,2026-03-01,0.093734,0.093650,0.093827,0.093738,-0.10
14,SEK,PLN,2026-02-26,0.395776,2026-03-01,0.395996,0.395449,0.396023,0.395811,0.06
15,SEK,RON,2026-02-26,0.477993,2026-03-01,0.477564,0.477149,0.477993,0.477598,-0.09
16,SEK,DKK,2026-02-26,0.700256,2026-03-01,0.699332,0.698955,0.700256,0.699540,-0.13
17,SEK,CZK,2026-02-26,2.273339,2026-03-01,2.272346,2.270960,2.273339,2.272258,-0.04
18,PLN,NOK,2026-02-26,2.675112,2026-03-01,2.655210,2.655210,2.675112,2.665380,-0.74
19,PLN,EUR,2026-02-26,0.237070,2026-03-01,0.236704,0.236701,0.237070,0.236824,-0.15
20,PLN,SEK,2026-02-26,2.526680,2026-03-01,2.525281,2.525107,2.528770,2.526460,-0.06
21,PLN,RON,2026-02-26,1.207736,2026-03-01,1.205984,1.205984,1.207736,1.206633,-0.15
22,PLN,DKK,2026-02-26,1.769323,2026-03-01,1.766011,1.766011,1.769323,1.767359,-0.19
23,PLN,CZK,2026-02-26,5.744001,2026-03-01,5.738310,5.738017,5.744001,5.740766,-0.10
24,RON,NOK,2026-02-26,2.214981,2026-03-01,2.201696,2.201696,2.214981,2.208938,-0.60
25,RON,EUR,2026-02-26,0.196293,2026-03-01,0.196275,0.196236,0.196293,0.196269,-0.01
26,RON,SEK,2026-02-26,2.092081,2026-03-01,2.093959,2.092081,2.095781,2.093810,0.09
27,RON,PLN,2026-02-26,0.827996,2026-03-01,0.829199,0.827996,0.829199,0.828753,0.15
28,RON,DKK,2026-02-26,1.464992,2026-03-01,1.464373,1.464373,1.464992,1.464703,-0.04
29,RON,CZK,2026-02-26,4.756009,2026-03-01,4.758198,4.756009,4.759435,4.757675,0.05
30,DKK,NOK,2026-02-26,1.511941,2026-03-01,1.503507,1.503507,1.511941,1.508112,-0.56
31,DKK,EUR,2026-02-26,0.133989,2026-03-01,0.134033,0.133986,0.134033,0.133999,0.03
32,DKK,SEK,2026-02-26,1.428049,2026-03-01,1.429935,1.428049,1.430707,1.429511,0.13
33,DKK,PLN,2026-02-26,0.565188,2026-03-01,0.566248,0.565188,0.566248,0.565816,0.19
34,DKK,RON,2026-02-26,0.682598,2026-03-01,0.682886,0.682598,0.682886,0.682732,0.04
35,DKK,CZK,2026-02-26,3.246440,2026-03-01,3.249307,3.246440,3.249307,3.248218,0.09
36,CZK,NOK,2026-02-26,0.465723,2026-03-01,0.462716,0.462716,0.465723,0.464289,-0.65
37,CZK,EUR,2026-02-26,0.041273,2026-03-01,0.041250,0.041238,0.041273,0.041253,-0.06
38,CZK,SEK,2026-02-26,0.439882,2026-03-01,0.440074,0.439882,0.440342,0.440091,0.04
39,CZK,PLN,2026-02-26,0.174095,2026-03-01,0.174267,0.174095,0.174276,0.174193,0.10
40,CZK,RON,2026-02-26,0.210260,2026-03-01,0.210164,0.210109,0.210260,0.210187,-0.05
41,CZK,DKK,2026-02-26,0.308030,2026-03-01,0.307758,0.307758,0.308030,0.307861,-0.09

In [236]:
cursor.execute(f"""
    CREATE VIEW IF NOT EXISTS fx_ytd_rates AS {ytd_query}
""")

In [235]:
# cursor.execute("""
#     DROP VIEW fx_ytd_rates
# """)

In [12]:
import os
import logging
import requests
import pandas as pd
from dotenv import load_dotenv
from datetime import datetime, timedelta

In [16]:
base_url = "https://v6.exchangerate-api.com/v6"
currencies = ['NOK', 'EUR', 'SEK', 'PLN', 'RON', 'DKK', 'CZK']

In [17]:
def latest_fx(base_url, currency="EUR") -> pd.DataFrame:
    """
    Get daily data 
    """
    # Get data 
    url = f"{base_url}/{api_key}/latest/{currency}"
    response = requests.get(url)
    response.raise_for_status()
    
    data = response.json()

    # Calculate cross pairs 
    records = []

    try:
        # Extract currencies rates
        rates = data["conversion_rates"]
        record = {"date" : datetime.today().strftime("%Y-%m-%d")}

        for currency in currencies:
            record[currency] = rates.get(currency)

        records.append(record)
        return pd.DataFrame(records)
        
    except Exception as e:
        logging.error(f"{datetime.today().strftime('%Y-%m-%d')} error: {e}")
        return pd.DataFrame()

In [18]:
latest_fx(base_url)

,date,NOK,EUR,SEK,PLN,RON,DKK,CZK
0,2026-03-02,11.184514,1,10.696146,4.231937,5.097253,7.460777,24.257334

In [ ]:
import sys
import os

sys.path.append(os.path.abspath(".."))  # ".." goes up one level

In [29]:
from dags.scripts.extract import latest_fx, history_fx
from itertools import permutations

In [30]:

def tranform_records(latest_or_history="Latest")-> pd.DataFrame:
    """
    if   fx_extract = latest_fx
        then it will return lastest date data
    elif fx_extract = history_fx
        then it will return history data
    """
    
    if   latest_or_history == 'Latest':
        df = latest_fx(base_url)
    elif latest_or_history == 'history':
        df = history_fx(base_url)

    cross_pairs = []
    for _, row in df.iterrows():
        for base, target in permutations(currencies, 2):
            rate = row[target] / row[base]
            cross_pairs.append({
                "date": row["date"],
                "base_currency": base,
                "target_currency": target,
                "rate": round(rate, 6)
            })
    
    df_pairs = pd.DataFrame(cross_pairs)
    return df_pairs

In [31]:
tranform_records()

          date base_currency target_currency       rate
0   2026-03-02           NOK             EUR   0.089409
1   2026-03-02           NOK             SEK   0.956335
2   2026-03-02           NOK             PLN   0.378375
3   2026-03-02           NOK             RON   0.455742
4   2026-03-02           NOK             DKK   0.667063
5   2026-03-02           NOK             CZK   2.168832
6   2026-03-02           EUR             NOK  11.184514
7   2026-03-02           EUR             SEK  10.696146
8   2026-03-02           EUR             PLN   4.231937
9   2026-03-02           EUR             RON   5.097253
10  2026-03-02           EUR             DKK   7.460777
11  2026-03-02           EUR             CZK  24.257334
12  2026-03-02           SEK             NOK   1.045658
13  2026-03-02           SEK             EUR   0.093492
14  2026-03-02           SEK             PLN   0.395651
15  2026-03-02           SEK             RON   0.476550
16  2026-03-02           SEK             DKK   0.697520
17  2026-03-02           SEK             CZK   2.267858
18  2026-03-02           PLN             NOK   2.642883
19  2026-03-02           PLN             EUR   0.236298
20  2026-03-02           PLN             SEK   2.527482
21  2026-03-02           PLN             RON   1.204473
22  2026-03-02           PLN             DKK   1.762970
23  2026-03-02           PLN             CZK   5.731970
24  2026-03-02           RON             NOK   2.194224
25  2026-03-02           RON             EUR   0.196184
26  2026-03-02           RON             SEK   2.098414
27  2026-03-02           RON             PLN   0.830239
28  2026-03-02           RON             DKK   1.463686
29  2026-03-02           RON             CZK   4.758903
30  2026-03-02           DKK             NOK   1.499109
31  2026-03-02           DKK             EUR   0.134034
32  2026-03-02           DKK             SEK   1.433650
33  2026-03-02           DKK             PLN   0.567225
34  2026-03-02           DKK             RON   0.683207
35  2026-03-02           DKK             CZK   3.251315
36  2026-03-02           CZK             NOK   0.461078
37  2026-03-02           CZK             EUR   0.041225
38  2026-03-02           CZK             SEK   0.440945
39  2026-03-02           CZK             PLN   0.174460
40  2026-03-02           CZK             RON   0.210132
41  2026-03-02           CZK             DKK   0.307568

In [34]:
from pathlib import Path
import sqlite3

In [53]:
import sqlite3
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO)

def run_dim_sql_folder(folder_path):
    files = []

    folder = Path(folder_path)
    if not folder.exists():
        raise FileNotFoundError(f"Folder {folder_path} not found")
    
    sql_files = folder.glob("*.sql")

    for file in sql_files:
        files.append(file)
    return files


db_path = "../../data/fx_warehouse.sqlite"
ddl_path = "../sql/ddl"

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

sql_files = run_dim_sql_folder(ddl_path)

try:
    for file in sql_files:
        sql_file = file.read_text()
        # print(sql_file)
        cursor.execute(sql_file)
        logging.info(f"Executed {file} successfully")
except Exception as e:
    logging.error(f"Error with {file}")